
export const JAPANESE_GRAMMAR_DATA: Record<string, GrammarExercise[]> = {
  pronombres_personales: [
    { type: 'match', question: "Yo", answer: "私 (Watashi)", options: ["私 (Watashi)", "あなた (Anata)", "彼 (Kare)", "彼女 (Kanojo)"] },
    { type: 'match', question: "Tú", answer: "あなた (Anata)", options: ["あなた (Anata)", "私 (Watashi)", "彼 (Kare)", "彼女 (Kanojo)"] },
    { type: 'match', question: "Él", answer: "彼 (Kare)", options: ["彼 (Kare)", "彼女 (Kanojo)", "私たち (Watashitachi)", "あなた (Anata)"] },
    { type: 'match', question: "Ella", answer: "彼女 (Kanojo)", options: ["彼女 (Kanojo)", "彼 (Kare)", "私たち (Watashitachi)", "あなた (Anata)"] },
    { type: 'match', question: "Nosotros", answer: "私たち (Watashitachi)", options: ["私たち (Watashitachi)", "あなたたち (Anatatachi)", "彼ら (Karera)", "彼女ら (Kanojora)"] },
    { type: 'match', question: "Ustedes", answer: "あなたたち (Anatatachi)", options: ["あなたたち (Anatatachi)", "私たち (Watashitachi)", "彼ら (Karera)", "彼女ら (Kanojora)"] },
    { type: 'match', question: "Ellos", answer: "彼ら (Karera)", options: ["彼ら (Karera)", "彼女ら (Kanojora)", "私たち (Watashitachi)", "あなたたち (Anatatachi)"] },
    { type: 'match', question: "Ellas", answer: "彼女ら (Kanojora)", options: ["彼女ら (Kanojora)", "彼ら (Karera)", "私たち (Watashitachi)", "あなたたち (Anatatachi)"] },
    { type: 'match', question: "Yo (informal masculino)", answer: "僕 (Boku)", options: ["僕 (Boku)", "私 (Watashi)", "俺 (Ore)", "君 (Kimi)"] },
    { type: 'match', question: "Yo (muy informal masculino)", answer: "俺 (Ore)", options: ["俺 (Ore)", "僕 (Boku)", "私 (Watashi)", "君 (Kimi)"] },
    { type: 'match', question: "Tú (informal)", answer: "君 (Kimi)", options: ["君 (Kimi)", "あなた (Anata)", "お前 (Omae)", "彼 (Kare)"] },
    { type: 'match', question: "Tú (muy informal)", answer: "お前 (Omae)", options: ["お前 (Omae)", "君 (Kimi)", "あなた (Anata)", "彼女 (Kanojo)"] },
    { type: 'match', question: "Aquel (él)", answer: "あの方 (Ano kata)", options: ["あの方 (Ano kata)", "あいつ (Aitsu)", "彼 (Kare)", "彼女 (Kanojo)"] },
    { type: 'match', question: "Aquella (ella)", answer: "あの方 (Ano kata)", options: ["あの方 (Ano kata)", "あいつ (Aitsu)", "彼女 (Kanojo)", "彼 (Kare)"] },
    { type: 'match', question: "Ese tipo (muy informal)", answer: "あいつ (Aitsu)", options: ["あいつ (Aitsu)", "あの方 (Ano kata)", "彼 (Kare)", "彼女 (Kanojo)"] }
  ],
  verbos_basicos: [
    { type: 'match', question: "Ir", answer: "行く (Iku)", options: ["行く (Iku)", "来る (Kuru)", "食べる (Taberu)", "飲む (Nomu)"] },
    { type: 'match', question: "Venir", answer: "来る (Kuru)", options: ["来る (Kuru)", "行く (Iku)", "帰る (Kaeru)", "走る (Hashiru)"] },
    { type: 'match', question: "Hablar", answer: "話す (Hanasu)", options: ["話す (Hanasu)", "聞く (Kiku)", "読む (Yomu)", "書く (Kaku)"] },
    { type: 'match', question: "Comer", answer: "食べる (Taberu)", options: ["食べる (Taberu)", "飲む (Nomu)", "寝る (Neru)", "起きる (Okiru)"] },
    { type: 'match', question: "Beber", answer: "飲む (Nomu)", options: ["飲む (Nomu)", "食べる (Taberu)", "買う (Kau)", "売る (Uru)"] },
    { type: 'match', question: "Estudiar", answer: "勉強する (Benkyou suru)", options: ["勉強する (Benkyou suru)", "練習する (Renshuu suru)", "仕事する (Shigoto suru)", "散歩する (Sanpo suru)"] },
    { type: 'match', question: "Trabajar", answer: "働く (Hataraku)", options: ["働く (Hataraku)", "遊ぶ (Asobu)", "休む (Yasumu)", "待つ (Matsu)"] },
    { type: 'match', question: "Bailar", answer: "踊る (Odoru)", options: ["踊る (Odoru)", "歌う (Utau)", "笑う (Warau)", "泣く (Naku)"] },
    { type: 'match', question: "Mirar", answer: "見る (Miru)", options: ["見る (Miru)", "見せる (Miseru)", "忘れる (Wasureru)", "覚える (Oboeru)"] },
    { type: 'match', question: "Viajar", answer: "旅行する (Ryokou suru)", options: ["旅行する (Ryokou suru)", "散歩する (Sanpo suru)", "買い物する (Kaimono suru)", "料理する (Ryouri suru)"] },
    { type: 'match', question: "Visitar", answer: "訪問する (Houmon suru)", options: ["訪問する (Houmon suru)", "招待する (Shoutai suru)", "紹介する (Shoukai suru)", "連絡する (Renraku suru)"] },
    { type: 'match', question: "Tener (objetos)", answer: "ある (Aru)", options: ["ある (Aru)", "いる (Iru)", "持っている (Motte iru)", "買う (Kau)"] },
    { type: 'match', question: "Tener/Estar (seres vivos)", answer: "いる (Iru)", options: ["いる (Iru)", "ある (Aru)", "住む (Sumu)", "行く (Iku)"] },
    { type: 'match', question: "Ser", answer: "です (Desu)", options: ["です (Desu)", "でした (Deshita)", "ます (Masu)", "ません (Masen)"] },
    { type: 'match', question: "Gustar", answer: "好き (Suki)", options: ["好き (Suki)", "嫌い (Kirai)", "上手 (Jouzu)", "下手 (Heta)"] },
    { type: 'match', question: "Querer (objeto)", answer: "欲しい (Hoshii)", options: ["欲しい (Hoshii)", "～たい (~tai)", "好き (Suki)", "上手 (Jouzu)"] },
    { type: 'match', question: "Querer (hacer algo)", answer: "～たい (~tai)", options: ["～たい (~tai)", "欲しい (Hoshii)", "～ます (~masu)", "～ない (~nai)"] },
    { type: 'match', question: "Estar (ubicación/estado)", answer: "あります/います (Arimasu/Imasu)", options: ["あります/います (Arimasu/Imasu)", "です (Desu)", "なります (Narimasu)", "します (Shimasu)"] }
  ],
  particulas_basicas: [
    { type: 'sentence', question: "Watashi ___ gakusei desu. (Yo soy estudiante)", answer: "wa", options: ["wa", "ni", "o", "ga"] },
    { type: 'sentence', question: "Ringo ___ tabemasu. (Como una manzana)", answer: "o", options: ["wa", "ni", "o", "de"] },
    { type: 'sentence', question: "Gakkou ___ ikimasu. (Voy a la escuela)", answer: "ni", options: ["wa", "ni", "o", "he"] },
    { type: 'sentence', question: "Toshokan ___ benkyou shimasu. (Estudio en la biblioteca)", answer: "de", options: ["de", "ni", "o", "wa"] },
    { type: 'sentence', question: "Kore ___ watashi no hon desu. (Este es mi libro)", answer: "wa", options: ["wa", "no", "ga", "ni"] },
    { type: 'sentence', question: "Tanaka-san ___ nihongo ga jouzu desu. (El Sr. Tanaka es bueno en japonés)", answer: "wa", options: ["wa", "ga", "no", "o"] },
    { type: 'sentence', question: "Nihon ___ ikitai desu. (Quiero ir a Japón)", answer: "ni", options: ["ni", "de", "o", "wa"] },
    { type: 'sentence', question: "Asagohan ___ pan o tabemashita. (Desayuné pan)", answer: "ni", options: ["ni", "de", "o", "wa"] },
    { type: 'sentence', question: "Kuruma ___ arimasu. (Hay un coche)", answer: "ga", options: ["ga", "wa", "o", "ni"] },
    { type: 'sentence', question: "Inu ___ imasu. (Hay un perro)", answer: "ga", options: ["ga", "wa", "o", "ni"] },
    { type: 'sentence', question: "Terebi ___ mimasu. (Miro la televisión)", answer: "o", options: ["o", "wa", "ga", "de"] },
    { type: 'sentence', question: "Uchi ___ kaerimasu. (Vuelvo a casa)", answer: "ni", options: ["ni", "he", "de", "o"] },
    { type: 'sentence', question: "Basu ___ ikimasu. (Voy en autobús)", answer: "de", options: ["de", "ni", "o", "he"] },
    { type: 'sentence', question: "Tomodachi ___ hanashimasu. (Hablo con un amigo)", answer: "to", options: ["to", "ni", "de", "o"] },
    { type: 'sentence', question: "Kyoto ___ kirei desu. (Kioto es hermoso)", answer: "wa", options: ["wa", "ga", "no", "ni"] }
  ],
  orden_frases: [
    { type: 'sentence_order', question: "Yo como una manzana", answer: "私 は りんご を 食べます", options: ["りんご", "を", "食べます", "私", "は"] },
    { type: 'sentence_order', question: "Voy a la escuela", answer: "学校 に 行きます", options: ["行きます", "学校", "に"] },
    { type: 'sentence_order', question: "Él habla japonés", answer: "彼 は 日本語 を 話します", options: ["話します", "日本語", "を", "彼", "は"] },
    { type: 'sentence_order', question: "Ella estudia en la biblioteca", answer: "彼女 は 図書館 で 勉強します", options: ["勉強します", "図書館", "で", "彼女", "は"] },
    { type: 'sentence_order', question: "Bailo en la fiesta", answer: "パーティー で 踊ります", options: ["踊ります", "パーティー", "で"] },
    { type: 'sentence_order', question: "Viajo a Japón", answer: "日本 に 旅行します", options: ["旅行します", "日本", "に"] },
    { type: 'sentence_order', question: "Miro la televisión", answer: "テレビ を 見ます", options: ["見ます", "テレビ", "を"] },
    { type: 'sentence_order', question: "Trabajo en la oficina", answer: "事務所 で 働きます", options: ["働きます", "事務所", "で"] },
    { type: 'sentence_order', question: "Bebo agua", answer: "水 を 飲みます", options: ["飲みます", "水", "を"] },
    { type: 'sentence_order', question: "Escucho música", answer: "音楽 を 聞きます", options: ["聞きます", "音楽", "を"] },
    { type: 'sentence_order', question: "Leo un libro", answer: "本 を 読みます", options: ["読みます", "本", "を"] },
    { type: 'sentence_order', question: "Escribo una carta", answer: "手紙 を 書きます", options: ["書きます", "手紙", "を"] },
    { type: 'sentence_order', question: "Compro pan", answer: "パン を 買います", options: ["買います", "パン", "を"] },
    { type: 'sentence_order', question: "Duermo en casa", answer: "家 で 寝ます", options: ["寝ます", "家", "で"] },
    { type: 'sentence_order', question: "Me levanto a las 7", answer: "七時 に 起きます", options: ["起きます", "七時", "に"] }
  ]
};

export const JAPANESE_VOCAB_DATA: Record<string, any[]> = {
  japones_basico: [
    { es: "Hola", jp: "こんにちは (Konnichiwa)" },
    { es: "Gracias", jp: "ありがとう (Arigatou)" },
    { es: "Sí", jp: "はい (Hai)" },
    { es: "No", jp: "いいえ (Iie)" },
    { es: "Por favor", jp: "お願いします (Onegaishimasu)" },
    { es: "Adiós", jp: "さようなら (Sayounara)" }
  ],
  presentarse_nombres: [
    { es: "Mucho gusto", jp: "はじめまして (Hajimemashite)" },
    { es: "Encantado de conocerte", jp: "どうぞよろしく (Douzo yoroshiku)" },
    { es: "Mi nombre es...", jp: "私の名前は...です (Watashi no namae wa ... desu)" },
    { es: "Nombre", jp: "名前 (Namae)" },
    { es: "Apellido", jp: "名字 (Myouji)" },
    { es: "¿Cómo te llamas?", jp: "お名前は何ですか？ (O-namae wa nan desu ka?)" },
    { es: "Soy [Nombre]", jp: "[Nombre] です ([Nombre] desu)" },
    { es: "Señor/Señora (Sufijo)", jp: "～さん (~san)" },
    { es: "Yo", jp: "私 (Watashi)" },
    { es: "Tú", jp: "あなた (Anata)" },
    { es: "Estudiante", jp: "学生 (Gakusei)" },
    { es: "Profesor", jp: "先生 (Sensei)" },
    { es: "Empleado", jp: "会社員 (Kaishain)" },
    { es: "Médico", jp: "医者 (Isha)" },
    { es: "Ingeniero", jp: "エンジニア (Enjinia)" }
  ],
  ciudad_y_edad: [
    { es: "Vivo en...", jp: "...に住んでいます (...ni sunde imasu)" },
    { es: "Ciudad", jp: "市 (Shi)" },
    { es: "Pueblo", jp: "町 (Machi)" },
    { es: "País", jp: "国 (Kuni)" },
    { es: "Japón", jp: "日本 (Nihon)" },
    { es: "España", jp: "スペイン (Supein)" },
    { es: "México", jp: "メキシコ (Mekishiko)" },
    { es: "Colombia", jp: "コロンビア (Koronbia)" },
    { es: "Argentina", jp: "アルゼンチン (Aruzenchin)" },
    { es: "Tengo ... años", jp: "...歳です (...sai desu)" },
    { es: "¿Cuántos años tienes?", jp: "何歳ですか？ (Nansai desu ka?)" },
    { es: "Edad", jp: "年齢 (Nenrei)" },
    { es: "Cumpleaños", jp: "誕生日 (Tanjoubi)" },
    { es: "Año", jp: "年 (Toshi)" },
    { es: "Mes", jp: "月 (Gatsu)" }
  ],
  familia_extendida: [
    { es: "Padre", jp: "父 (Chichi)" },
    { es: "Madre", jp: "母 (Haha)" },
    { es: "Hermano mayor", jp: "兄 (Ani)" },
    { es: "Hermana mayor", jp: "姉 (Ane)" },
    { es: "Hermano menor", jp: "弟 (Otouto)" },
    { es: "Hermana menor", jp: "妹 (Imouto)" },
    { es: "Abuelo", jp: "祖父 (Sofu)" },
    { es: "Abuela", jp: "祖母 (Sobo)" },
    { es: "Tío", jp: "叔父 (Oji)" },
    { es: "Tía", jp: "叔母 (Oba)" },
    { es: "Primo/a", jp: "いとこ (Itoko)" },
    { es: "Hijo", jp: "息子 (Musuko)" },
    { es: "Hija", jp: "娘 (Musume)" },
    { es: "Esposo", jp: "夫 (Otto)" },
    { es: "Esposa", jp: "妻 (Tsuma)" }
  ],
  numeros_1_20: [
    { es: "Uno", jp: "一 (Ichi)" },
    { es: "Dos", jp: "二 (Ni)" },
    { es: "Tres", jp: "三 (San)" },
    { es: "Cuatro", jp: "四 (Yon/Shi)" },
    { es: "Cinco", jp: "五 (Go)" },
    { es: "Seis", jp: "六 (Roku)" },
    { es: "Siete", jp: "七 (Nana/Shichi)" },
    { es: "Ocho", jp: "八 (Hachi)" },
    { es: "Nueve", jp: "九 (Kyuu/Ku)" },
    { es: "Diez", jp: "十 (Juu)" },
    { es: "Once", jp: "十一 (Juu-ichi)" },
    { es: "Doce", jp: "十二 (Juu-ni)" },
    { es: "Trece", jp: "十三 (Juu-san)" },
    { es: "Catorce", jp: "十四 (Juu-yon)" },
    { es: "Quince", jp: "十五 (Juu-go)" },
    { es: "Dieciséis", jp: "十六 (Juu-roku)" },
    { es: "Diecisiete", jp: "十七 (Juu-nana)" },
    { es: "Dieciocho", jp: "十八 (Juu-hachi)" },
    { es: "Diecinueve", jp: "十九 (Juu-kyuu)" },
    { es: "Veinte", jp: "二十 (Ni-juu)" }
  ],
  numeros_21_100: [
    { es: "Veintiuno", jp: "二十一 (Ni-juu-ichi)" },
    { es: "Treinta", jp: "三十 (San-juu)" },
    { es: "Cuarenta", jp: "四十 (Yon-juu)" },
    { es: "Cincuenta", jp: "五十 (Go-juu)" },
    { es: "Sesenta", jp: "六十 (Roku-juu)" },
    { es: "Setenta", jp: "七十 (Nana-juu)" },
    { es: "Ochenta", jp: "八十 (Hachi-juu)" },
    { es: "Noventa", jp: "九十 (Kyuu-juu)" },
    { es: "Cien", jp: "百 (Hyaku)" },
    { es: "Treinta y cinco", jp: "三十五 (San-juu-go)" },
    { es: "Cuarenta y dos", jp: "四十二 (Yon-juu-ni)" },
    { es: "Cincuenta y ocho", jp: "五十八 (Go-juu-hachi)" },
    { es: "Sesenta y cuatro", jp: "六十四 (Roku-juu-yon)" },
    { es: "Setenta y siete", jp: "七十七 (Nana-juu-nana)" },
    { es: "Ochenta y nueve", jp: "八十九 (Hachi-juu-kyuu)" }
  ],
  la_ciudad_edificios: [
    { es: "Estación", jp: "駅 (Eki)" },
    { es: "Banco", jp: "銀行 (Ginkou)" },
    { es: "Hospital", jp: "病院 (Byouin)" },
    { es: "Escuela", jp: "学校 (Gakkou)" },
    { es: "Restaurante", jp: "レストラン (Resutoran)" },
    { es: "Supermercado", jp: "スーパー (Suupaa)" },
    { es: "Parque", jp: "公園 (Kouen)" },
    { es: "Biblioteca", jp: "図書館 (Toshokan)" },
    { es: "Museo", jp: "美術館 (Bijutsukan)" },
    { es: "Hotel", jp: "ホテル (Hoteru)" },
    { es: "Tienda", jp: "店 (Mise)" },
    { es: "Cine", jp: "映画館 (Eigakan)" },
    { es: "Templo", jp: "寺 (Tera)" },
    { es: "Santuario", jp: "神社 (Jinja)" },
    { es: "Castillo", jp: "城 (Jou)" }
  ],
  describir_ciudad: [
    { es: "Grande", jp: "大きい (Ookii)" },
    { es: "Pequeño", jp: "小さい (Chiisai)" },
    { es: "Hermoso", jp: "きれい (Kirei)" },
    { es: "Famoso", jp: "有名 (Yuumei)" },
    { es: "Ruidoso", jp: "にぎやか (Nigiyaka)" },
    { es: "Tranquilo", jp: "静か (Shizuka)" },
    { es: "Conveniente", jp: "便利 (Benri)" },
    { es: "Inconveniente", jp: "不便 (Fuben)" },
    { es: "Nuevo", jp: "新しい (Atarashii)" },
    { es: "Viejo", jp: "古い (Furui)" },
    { es: "Cerca", jp: "近い (Chikai)" },
    { es: "Lejos", jp: "遠い (Tooi)" },
    { es: "Muchos", jp: "多い (Ooi)" },
    { es: "Pocos", jp: "少ない (Sukunai)" },
    { es: "Interesante", jp: "面白い (Omoshiroi)" }
  ],
  pedir_ayuda: [
    { es: "Ayuda, por favor", jp: "助けてください (Tasukete kudasai)" },
    { es: "Disculpe", jp: "すみません (Sumimasen)" },
    { es: "No entiendo", jp: "わかりません (Wakarimasen)" },
    { es: "¿Dónde está ...?", jp: "...はどこですか？ (... wa doko desu ka?)" },
    { es: "¿Puede hablar más despacio?", jp: "ゆっくり話してください (Yukkuri hanashite kudasai)" },
    { es: "¿Qué significa esto?", jp: "これはどういう意味ですか？ (Kore wa dou iu imi desu ka?)" },
    { es: "He perdido mi camino", jp: "道に迷いました (Michi ni mayoimashita)" },
    { es: "Por favor, escriba aquí", jp: "ここに書いてください (Koko ni kaite kudasai)" },
    { es: "¿Hay alguien que hable español?", jp: "スペイン語を話せる人はいますか？ (Supeingo o hanaseru hito wa imasu ka?)" },
    { es: "Llamen a un médico", jp: "医者を呼んでください (Isha o yonde kudasai)" },
    { es: "He perdido mi pasaporte", jp: "パスポートをなくしました (Pasupooto o nakushimashita)" },
    { es: "¿Puedo usar el teléfono?", jp: "電話を借りてもいいですか？ (Denwa o karitemo ii desu ka?)" },
    { es: "Está bien", jp: "大丈夫です (Daijoubu desu)" },
    { es: "No está bien", jp: "大丈夫じゃないです (Daijoubu janai desu)" },
    { es: "Por favor, espere", jp: "待ってください (Matte kudasai)" }
  ]
};

export const JAPANESE_NUMBER_DATA = {
  all: [
    { val: "1", es: "Uno", jp: "一 (Ichi)" },
    { val: "2", es: "Dos", jp: "二 (Ni)" },
    { val: "3", es: "Tres", jp: "三 (San)" },
    { val: "4", es: "Cuatro", jp: "四 (Yon/Shi)" },
    { val: "5", es: "Cinco", jp: "五 (Go)" },
    { val: "6", es: "Seis", jp: "六 (Roku)" },
    { val: "7", es: "Siete", jp: "七 (Nana/Shichi)" },
    { val: "8", es: "Ocho", jp: "八 (Hachi)" },
    { val: "9", es: "Nueve", jp: "九 (Kyuu/Ku)" },
    { val: "10", es: "Diez", jp: "十 (Juu)" },
    { val: "11", es: "Once", jp: "十一 (Juu-ichi)" },
    { val: "12", es: "Doce", jp: "十二 (Juu-ni)" },
    { val: "13", es: "Trece", jp: "十三 (Juu-san)" },
    { val: "14", es: "Catorce", jp: "十四 (Juu-yon)" },
    { val: "15", es: "Quince", jp: "十五 (Juu-go)" },
    { val: "16", es: "Dieciséis", jp: "十六 (Juu-roku)" },
    { val: "17", es: "Diecisiete", jp: "十七 (Juu-nana)" },
    { val: "18", es: "Dieciocho", jp: "十八 (Juu-hachi)" },
    { val: "19", es: "Diecinueve", jp: "十九 (Juu-kyuu)" },
    { val: "20", es: "Veinte", jp: "二十 (Ni-juu)" },
    { val: "30", es: "Treinta", jp: "三十 (San-juu)" },
    { val: "40", es: "Cuarenta", jp: "四十 (Yon-juu)" },
    { val: "50", es: "Cincuenta", jp: "五十 (Go-juu)" },
    { val: "60", es: "Sesenta", jp: "六十 (Roku-juu)" },
    { val: "70", es: "Setenta", jp: "七十 (Nana-juu)" },
    { val: "80", es: "Ochenta", jp: "八十 (Hachi-juu)" },
    { val: "90", es: "Noventa", jp: "九十 (Kyuu-juu)" },
    { val: "100", es: "Cien", jp: "百 (Hyaku)" }
  ]
};

export const JAPANESE_WRITING_DATA: Record<string, any[]> = {
  hiragana_basico: [
    { es: "A", jp: "あ" },
    { es: "I", jp: "い" },
    { es: "U", jp: "う" },
    { es: "E", jp: "え" },
    { es: "O", jp: "お" }
  ]
};

export interface GrammarExercise {
  type: 'drill' | 'sentence' | 'match' | 'roleplay' | 'sentence_order';
  question: string;
  answer: string;
  options: string[];
  clue?: string;
  context?: string;
  hint?: string;
}

export const GRAMMAR_DATA: Record<string, GrammarExercise[]> = {
  pronombres_personales: [
    { type: 'match', question: "I", answer: "Yo", options: ["Yo", "Tú", "Él", "Nosotros"] },
    { type: 'match', question: "You (informal)", answer: "Tú", options: ["Tú", "Usted", "Vosotros", "Ellos"] },
    { type: 'match', question: "He", answer: "Él", options: ["Él", "Ella", "Nosotros", "Usted"] },
    { type: 'match', question: "She", answer: "Ella", options: ["Ella", "Él", "Nosotras", "Ellos"] },
    { type: 'match', question: "You (formal)", answer: "Usted", options: ["Usted", "Tú", "Él", "Nosotros"] },
    { type: 'match', question: "We (m)", answer: "Nosotros", options: ["Nosotros", "Nosotras", "Ustedes", "Ellos"] },
    { type: 'match', question: "We (f)", answer: "Nosotras", options: ["Nosotras", "Nosotros", "Vosotras", "Ellas"] },
    { type: 'match', question: "You all (Spain/m)", answer: "Vosotros", options: ["Vosotros", "Ustedes", "Nosotros", "Ellos"] },
    { type: 'match', question: "You all (Spain/f)", answer: "Vosotras", options: ["Vosotras", "Vosotros", "Nosotras", "Ellas"] },
    { type: 'match', question: "They (m)", answer: "Ellos", options: ["Ellos", "Ellas", "Ustedes", "Nosotros"] },
    { type: 'match', question: "They (f)", answer: "Ellas", options: ["Ellas", "Ellos", "Ustedes", "Nosotras"] },
    { type: 'match', question: "You all (L.Am)", answer: "Ustedes", options: ["Ustedes", "Vosotros", "Ellos", "Nosotros"] }
  ],
  ser: [
    { type: 'sentence', question: "Yo ___ profesor.", answer: "soy", options: ["soy", "eres", "es", "somos"] },
    { type: 'sentence', question: "Tú ___ mi mejor amigo.", answer: "eres", options: ["soy", "eres", "es", "somos"] },
    { type: 'sentence', question: "Él ___ inteligente.", answer: "es", options: ["soy", "eres", "es", "somos"] },
    { type: 'sentence', question: "Ella ___ doctora.", answer: "es", options: ["soy", "eres", "es", "somos"] },
    { type: 'sentence', question: "Nosotros ___ de España.", answer: "somos", options: ["soy", "eres", "es", "somos"] },
    { type: "sentence", question: "Vosotros ___ estudiantes.", answer: "sois", options: ["soy", "sois", "son", "somos"] },
    { type: "sentence", question: "Ellos ___ mis hermanos.", answer: "son", options: ["soy", "eres", "es", "son"] },
    { type: "sentence", question: "Ustedes ___ bienvenidos.", answer: "son", options: ["soy", "eres", "es", "son"] },
    { type: "sentence", question: "La casa ___ blanca.", answer: "es", options: ["es", "son", "soy", "eres"] },
    { type: "sentence", question: "Nosotras ___ amigas.", answer: "somos", options: ["somos", "sois", "son", "soy"] }
  ],
  estar: [
    { type: 'sentence', question: "Yo ___ en casa.", answer: "estoy", options: ["estoy", "estás", "está", "estamos"] },
    { type: 'sentence', question: "Tú ___ feliz hoy.", answer: "estás", options: ["estoy", "estás", "está", "estamos"] },
    { type: "sentence", question: "Él ___ en Madrid.", answer: "está", options: ["estoy", "estás", "está", "estamos"] },
    { type: "sentence", question: "Nosotros ___ cansados.", answer: "estamos", options: ["estoy", "estás", "está", "estamos"] },
    { type: "sentence", question: "Vosotros ___ en el parque.", answer: "estáis", options: ["estoy", "estáis", "está", "estamos"] },
    { type: "sentence", question: "Ellos ___ ocupados.", answer: "están", options: ["estoy", "estás", "están", "estamos"] },
    { type: "sentence", question: "Ella ___ enferma.", answer: "está", options: ["estoy", "está", "están", "estamos"] },
    { type: 'sentence', question: "Ustedes ___ listos.", answer: "están", options: ["estoy", "estás", "están", "estamos"] },
    { type: 'sentence', question: "El libro ___ en la mesa.", answer: "está", options: ["estoy", "está", "están", "estamos"] },
    { type: 'sentence', question: "Nosotras ___ aquí.", answer: "estamos", options: ["estamos", "estáis", "están", "estoy"] }
  ],
  tener: [
    { type: 'sentence', question: "Yo ___ un perro.", answer: "tengo", options: ["tengo", "tienes", "tiene", "tenemos"] },
    { type: 'sentence', question: "Tú ___ veinte años.", answer: "tienes", options: ["tengo", "tienes", "tiene", "tenemos"] },
    { type: 'sentence', question: "Él ___ mucho calor.", answer: "tiene", options: ["tengo", "tienes", "tiene", "tenemos"] },
    { type: 'sentence', question: "Nosotros ___ una casa grande.", answer: "tenemos", options: ["tengo", "tienes", "tiene", "tenemos"] },
    { type: 'sentence', question: "Vosotros ___ hambre.", answer: "tenéis", options: ["tengo", "tenéis", "tiene", "tenemos"] },
    { type: 'sentence', question: "Ellos ___ sed.", answer: "tienen", options: ["tengo", "tienes", "tienen", "tenemos"] },
    { type: 'sentence', question: "Ella ___ un gato blanco.", answer: "tiene", options: ["tengo", "tiene", "tienen", "tenemos"] },
    { type: 'sentence', question: "Ustedes ___ tiempo libre.", answer: "tienen", options: ["tengo", "tienes", "tienen", "tenemos"] },
    { type: 'sentence', question: "Yo ___ mucha suerte.", answer: "tengo", options: ["tengo", "tienes", "tiene", "tenemos"] },
    { type: "sentence", question: "Nosotras ___ un examen hoy.", answer: "tenemos", options: ["tenemos", "tenéis", "tienen", "tengo"] }
  ],
  regulares_ar: [
    { type: 'sentence', question: "Yo ___ español.", answer: "hablo", options: ["hablo", "hablas", "habla", "hablan"] },
    { type: 'sentence', question: "Tú ___ por la playa.", answer: "caminas", options: ["camino", "caminas", "camina", "caminan"] },
    { type: 'sentence', question: "Él ___ muy bien.", answer: "baila", options: ["bailo", "baila", "bailas", "bailan"] },
    { type: 'sentence', question: "Nosotros ___ una canción.", answer: "cantamos", options: ["canto", "canta", "cantamos", "cantan"] },
    { type: 'sentence', question: "Vosotros ___ música.", answer: "escucháis", options: ["escucho", "escuchas", "escucháis", "escuchan"] },
    { type: 'sentence', question: "Ellos ___ comida.", answer: "compran", options: ["compro", "compra", "compran", "compramos"] },
    { type: 'sentence', question: "Ella ___ para el examen.", answer: "estudia", options: ["estudio", "estudia", "estudias", "estudian"] },
    { type: 'sentence', question: "Usted ___ las llaves.", answer: "busca", options: ["busco", "buscas", "busca", "buscan"] },
    { type: 'sentence', question: "Ustedes ___ en la oficina.", options: ["trabajo", "trabaja", "trabajamos", "trabajan"], answer: "trabajan" }, 
    { type: 'sentence', question: "Nosotras ___ mucho.", answer: "practicamos", options: ["practico", "practica", "practicamos", "practican"] }
  ],
  regulares_er: [
    { type: 'sentence', question: "Yo ___ una manzana.", answer: "como", options: ["como", "comes", "come", "comen"] },
    { type: 'sentence', question: "Tú ___ agua fría.", answer: "bebes", options: ["bebo", "bebes", "bebe", "beben"] },
    { type: 'sentence', question: "Él ___ un libro.", answer: "lee", options: ["leo", "lees", "lee", "leen"] },
    { type: 'sentence', question: "Nosotros ___ español.", answer: "aprendemos", options: ["aprendo", "aprende", "aprendemos", "aprenden"] },
    { type: 'sentence', question: "Vosotros ___ el coche.", answer: "vendéis", options: ["vendo", "vendes", "vendéis", "venden"] },
    { type: 'sentence', question: "Ellos ___ en el parque.", answer: "corren", options: ["corro", "corres", "corre", "corren"] },
    { type: 'sentence', question: "Ella ___ en Dios.", answer: "cree", options: ["creo", "crees", "cree", "creen"] },
    { type: 'sentence', question: "Usted ___ la pregunta.", answer: "responde", options: ["respondo", "respondes", "responde", "responden"] },
    { type: 'sentence', question: "Ustedes ___ todo.", answer: "comprenden", options: ["comprendo", "comprende", "comprendemos", "comprenden"] },
    { type: "sentence", question: "Nosotras ___ el silencio.", answer: "rompemos", options: ["rompo", "rompes", "rompemos", "rompen"] }
  ],
  regulares_ir: [
    { type: 'sentence', question: "Yo ___ en Madrid.", answer: "vivo", options: ["vivo", "vives", "vive", "viven"] },
    { type: 'sentence', question: "Tú ___ una carta.", answer: "escribes", options: ["escribo", "escribes", "escribe", "escriben"] },
    { type: 'sentence', question: "Él ___ la puerta.", answer: "abre", options: ["abro", "abres", "abre", "abrimos"] },
    { type: 'sentence', question: "Nosotros ___ el pastel.", answer: "compartimos", options: ["comparto", "comparte", "compartimos", "comparten"] },
    { type: 'sentence', question: "Vosotros ___ el futuro.", answer: "decidís", options: ["decido", "decides", "decidís", "deciden"] },
    { type: 'sentence', question: "Ellos ___ un regalo.", answer: "reciben", options: ["recibo", "recibes", "recibe", "reciben"] },
    { type: 'sentence', question: "Ella ___ las escaleras.", answer: "sube", options: ["subo", "subes", "sube", "suben"] },
    { type: 'sentence', question: "Usted ___ el paso.", answer: "permite", options: ["permito", "permite", "permites", "permiten"] },
    { type: 'sentence', question: "Ustedes ___ el tema.", answer: "discuten", options: ["discuto", "discute", "discutimos", "discuten"] },
    { type: 'sentence', question: "Nosotras ___ ahora.", answer: "partimos", options: ["parto", "partes", "parte", "partimos"] }
  ],
  verbos_mixtos_ar_er_ir: [
    { type: 'sentence', question: "Yo ___ español muy bien.", answer: "hablo", options: ["hablo", "habla", "hablan", "hablas"] },
    { type: 'sentence', question: "Tú ___ una manzana roja.", answer: "comes", options: ["como", "come", "comes", "comen"] },
    { type: 'sentence', question: "Él ___ en Madrid.", answer: "vive", options: ["vivo", "vives", "vive", "viven"] },
    { type: 'sentence', question: "Nosotros ___ una canción.", answer: "cantamos", options: ["cantamos", "canta", "cantan", "cantáis"] },
    { type: 'sentence', question: "Vosotros ___ mucha agua.", answer: "bebéis", options: ["bebo", "bebemos", "bebéis", "beben"] },
    { type: 'sentence', question: "Ellas ___ una carta.", answer: "escriben", options: ["escribo", "escribes", "escribe", "escriben"] },
    { type: 'sentence', question: "Yo ___ al parque.", answer: "camino", options: ["camino", "caminas", "camina", "caminan"] },
    { type: 'sentence', question: "Tú ___ muy rápido.", answer: "corres", options: ["corro", "corres", "corre", "corren"] },
    { type: 'sentence', question: "Él ___ la puerta.", answer: "abre", options: ["abro", "abres", "abre", "abrimos"] },
    { type: 'sentence', question: "Nosotros ___ medicina.", answer: "estudiamos", options: ["estudio", "estudias", "estudiamos", "estudian"] },
    { type: 'sentence', question: "Vosotros ___ español.", answer: "aprendéis", options: ["aprendo", "aprendemos", "aprendéis", "aprenden"] },
    { type: 'sentence', question: "Ellas ___ la escalera.", answer: "suben", options: ["subo", "subes", "sube", "suben"] },
    { type: 'sentence', question: "Yo ___ música latina.", answer: "escucho", options: ["escucho", "escuchas", "escucha", "escuchan"] },
    { type: 'sentence', question: "Tú ___ un libro.", answer: "lees", options: ["leo", "lees", "lee", "leen"] },
    { type: 'sentence', question: "Él ___ un regalo.", answer: "recibe", options: ["recibo", "recibes", "recibe", "recibimos"] },
    { type: 'sentence', question: "Nosotros ___ salsa.", answer: "bailamos", options: ["bailo", "bailamos", "bailan", "baila"] },
    { type: 'sentence', question: "Vosotros ___ la casa.", answer: "vendéis", options: ["vendo", "vendes", "vendemos", "vendéis"] },
    { type: 'sentence', question: "Ellas ___ el pastel.", answer: "parten", options: ["parto", "partes", "parte", "parten"] },
    { type: 'sentence', question: "Yo ___ pan fresco.", answer: "compro", options: ["compro", "compras", "compra", "compran"] },
    { type: 'sentence', question: "Tú ___ la pregunta.", answer: "respondes", options: ["respondo", "respondes", "responde", "responden"] }
  ],
  verb_gustar: [
    { type: 'sentence', question: "A mí ___ la mañana.", answer: "me gusta", options: ["me gusta", "me gustan", "te gusta", "nos gusta"] },
    { type: 'sentence', question: "A mí ___ la noche.", answer: "me gusta", options: ["me gusta", "me gustan", "te gusta", "nos gusta"] },
    { type: 'sentence', question: "A mí ___ el mar.", answer: "me gusta", options: ["me gusta", "me gustan", "te gusta", "nos gusta"] },
    { type: 'sentence', question: "A mí ___ la playa.", answer: "me gusta", options: ["me gusta", "me gustan", "te gusta", "nos gusta"] },
    { type: 'sentence', question: "A mí ___ las frutas.", answer: "me gustan", options: ["me gusta", "me gustan", "te gusta", "nos gusta"] },
    { type: 'sentence', question: "A mí ___ las verduras.", answer: "me gustan", options: ["me gusta", "me gustan", "te gusta", "nos gusta"] },
    { type: 'match', question: "The verb 'to like'", answer: "El verbo gustar", options: ["El verbo ser", "El verbo estar", "El verbo tener", "El verbo gustar"] },
    { type: 'match', question: "I like (singular object/infinitive)", answer: "Me gusta", options: ["Me gustan", "Te gusta", "Nos gusta", "Me gusta"] },
    { type: 'match', question: "You (informal) like (singular object/infinitive)", answer: "Te gusta", options: ["Me gusta", "Te gustan", "Le gusta", "Te gusta"] },
    { type: 'match', question: "He/She/You (formal) like (singular object/infinitive)", answer: "Le gusta", options: ["Nos gusta", "Les gusta", "Le gusta", "Te gusta"] },
    { type: 'match', question: "We like (singular object/infinitive)", answer: "Nos gusta", options: ["Me gusta", "Os gusta", "Nos gusta", "Les gusta"] },
    { type: 'match', question: "You all (Spain) like (singular object/infinitive)", answer: "Os gusta", options: ["Nos gusta", "Les gusta", "Os gusta", "Te gusta"] },
    { type: 'match', question: "They/You all (L.Am) like (singular object/infinitive)", answer: "Les gusta", options: ["Nos gusta", "Os gusta", "Les gusta", "Le gusta"] },
    { type: 'sentence', question: "A nosotros ___ España.", answer: "nos gusta", options: ["nos gusta", "nos gustan", "os gusta", "les gusta"] },
    { type: 'sentence', question: "A vosotros ___ España.", answer: "os gusta", options: ["os gusta", "os gustan", "nos gusta", "les gusta"] },
    { type: 'sentence', question: "A ellos ___ España.", answer: "les gusta", options: ["les gusta", "les gustan", "nos gusta", "os gusta"] },
    { type: 'sentence', question: "A ti ___ la chica.", answer: "te gusta", options: ["te gusta", "te gustan", "me gusta", "le gusta"] },
    { type: 'sentence', question: "A él/ella ___ tu amiga.", answer: "le gusta", options: ["le gusta", "le gustan", "te gusta", "nos gusta"] },
    { type: 'sentence', question: "A nosotros ___ el español.", answer: "nos gusta", options: ["nos gusta", "nos gustan", "os gusta", "les gusta"] },
    { type: 'sentence', question: "¿A vosotros ___ la escuela?", answer: "os gusta", options: ["os gusta", "os gustan", "nos gusta", "les gusta"] },
    { type: 'sentence', question: "A ellos ___ estudiar.", answer: "les gusta", options: ["les gusta", "les gustan", "nos gusta", "os gusta"] },
    { type: 'match', question: "Let's speak Spanish", answer: "Hablemos español", options: ["Hablar español", "Estudiemos español", "Leamos español", "Hablemos español"] },
    { type: 'sentence', question: "¿Qué alimentos ___ (a ti)?", answer: "te gustan", options: ["te gusta", "te gustan", "me gusta", "nos gusta"] },
    { type: 'sentence', question: "A mí ___ la pasta.", answer: "me gusta", options: ["me gusta", "me gustan", "te gusta", "nos gusta"] }
  ],
  tener_expressions: [
    { type: 'sentence', question: "Hace sol y yo ___ mucho ___.", answer: "tengo calor", options: ["tengo calor", "tengo frío", "tengo hambre", "tengo sed"] },
    { type: 'sentence', question: "Es invierno y ellos ___ mucho ___.", answer: "tienen frío", options: ["tienen frío", "tienen calor", "tienen prisa", "tienen razón"] },
    { type: 'sentence', question: "¡___ ___ con el coche!", answer: "Ten cuidado", options: ["Ten cuidado", "Ten prisa", "Ten suerte", "Ten razón"] },
    { type: 'sentence', question: "No he comido nada, ___ mucha ___.", answer: "tengo hambre", options: ["tengo hambre", "tengo sed", "tengo miedo", "tengo prisa"] },
    { type: 'sentence', question: "Necesito agua, ___ mucha ___.", answer: "tengo sed", options: ["tengo sed", "tengo hambre", "tengo sueño", "tengo calor"] },
    { type: 'sentence', question: "Ella ___ ___ de las arañas.", answer: "tiene miedo", options: ["tiene miedo", "tiene sueño", "tiene razón", "tiene suerte"] },
    { type: 'sentence', question: "El tren sale pronto, nosotros ___ ___.", answer: "tenemos prisa", options: ["tenemos prisa", "tenemos razón", "tenemos sueño", "tenemos sed"] },
    { type: 'sentence', question: "Tú siempre ___ ___, el cielo es azul.", answer: "tienes razón", options: ["tienes razón", "tienes prisa", "tienes miedo", "tienes calor"] },
    { type: 'sentence', question: "¡Ganaste la lotería! ___ mucha ___.", answer: "Tienes suerte", options: ["Tienes suerte", "Tienes razón", "Tienes prisa", "Tienes frío"] },
    { type: 'sentence', question: "Yo ___ ___ ___ ir a la playa.", answer: "tengo ganas de", options: ["tengo ganas de", "tengo que", "tengo miedo de", "tengo prisa por"] },
    { type: 'sentence', question: "Mañana hay examen, ___ ___ estudiar.", answer: "tengo que", options: ["tengo que", "tengo ganas de", "tengo miedo de", "tengo suerte de"] }
  ],
  expresiones_con_doler: [
    { type: 'sentence', question: "¿Qué ___ duele?", answer: "te", options: ["te", "me", "le", "nos"] },
    { type: 'sentence', question: "Me ___ la cabeza.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ el estómago.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ la barriga.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ la espalda.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ los oídos.", answer: "duelen", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ las orejas.", answer: "duelen", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ el oído.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ la oreja.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ los ojos.", answer: "duelen", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ el ojo.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ el pie.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ la pierna.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ la rodilla.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ las rodillas.", answer: "duelen", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ los pies.", answer: "duelen", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ los huesos.", answer: "duelen", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ los músculos.", answer: "duelen", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ el corazón.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ el pecho.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ el pulmón.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ la garganta.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ el hombro.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "Me ___ el codo.", answer: "duele", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "A él ___ duele la cabeza.", answer: "le", options: ["me", "te", "le", "nos"] },
    { type: 'sentence', question: "A nosotros ___ duele el estómago.", answer: "nos", options: ["me", "te", "le", "nos"] },
    { type: 'sentence', question: "¿Te ___ los pies?", answer: "duelen", options: ["duele", "duelen", "dueles", "duelo"] },
    { type: 'sentence', question: "A ellas ___ duele la espalda.", answer: "les", options: ["le", "les", "nos", "os"] },
    { type: 'sentence', question: "A mí ___ duele el cuello.", answer: "me", options: ["me", "te", "le", "nos"] },
    { type: 'sentence', question: "¿Qué ___ duele a usted?", answer: "le", options: ["me", "te", "le", "nos"] }
  ]
};

const getImageUrl = (keyword: string, seed: number) => `https://source.unsplash.com/random/300x200/?${keyword}&sig=${seed}`;

export const VOCAB_DATA: Record<string, any[]> = {
  espanol_basico: [
    { es: "Teléfono", en: "Phone" },
    { es: "Guitarra", en: "Guitar" },
    { es: "Fiesta", en: "Party" },
    { es: "Bar", en: "Bar" },
    { es: "Hospital", en: "Hospital" },
    { es: "Hotel", en: "Hotel" },
    { es: "Artista", en: "Artist" },
    { es: "Catedral", en: "Cathedral" },
    { es: "Chocolate", en: "Chocolate" },
    { es: "Estación", en: "Station" },
    { es: "Oficina", en: "Office" },
    { es: "Monumento", en: "Monument" },
    { es: "Foto", en: "Photo" },
    { es: "Pasaporte", en: "Passport" },
    { es: "Familia", en: "Family" },
    { es: "Taxi", en: "Taxi" },
    { es: "Policía", en: "Police" },
    { es: "Televisión", en: "Television" },
    { es: "Museo", en: "Museo" },
    { es: "Paella", en: "Paella" },
    { es: "Hola", en: "Hello" },
    { es: "Adiós", en: "Goodbye" },
    { es: "Sí", en: "Yes" },
    { es: "No", en: "No" },
    { es: "Por favor", en: "Please" },
    { es: "Gracias", en: "Thank you" },
    { es: "De nada", en: "You're welcome" },
    { es: "Aquí tiene", en: "Here you go" },
    { es: "Buenos días", en: "Good morning" },
    { es: "Buenas tardes", en: "Good afternoon" },
    { es: "Buenas noches", en: "Good evening" }
  ],
  reto_introducing_yourself: [
    { es: "¿Cómo te llamas?", en: "What's your name?" },
    { es: "¿De dónde eres?", en: "Where are you from?" },
    { es: "¿Cuántos años tienes?", en: "How old are you?" },
    { es: "¿Dónde vives?", en: "Where do you live?" },
    { es: "¿Cuál es tu dirección?", en: "What's your address?" },
    { es: "¿Cuál es tu código postal?", en: "What's your zip code?" },
    { es: "¿Cuál es tu correo electrónico?", en: "What's your email?" },
    { es: "Mi número de teléfono es…", en: "My phone number is..." },
    { es: "¿Qué tal?", en: "How's it going?" },
    { es: "¿Cómo estás?", en: "How are you (informal)?" },
    { es: "¿Cómo está?", en: "How are you (formal)?" },
    { es: "Muy bien", en: "Very good" },
    { es: "Bien", en: "Good" },
    { es: "Regular", en: "Okay / So-so" },
    { es: "Mal", en: "Bad" },
    { es: "Muy mal", en: "Very bad" },
    { es: "Fatal", en: "Terrible" },
    { es: "¿Y tú?", en: "And you (informal)?" },
    { es: "Y", en: "And" },
    { es: "Yo, bien también", en: "I'm good too" },
    { es: "También", en: "Also / Too" }
  ],
  familia: [
    { es: "Padre", en: "Father" },
    { es: "Madre", en: "Mother" },
    { es: "Abuela", en: "Grandmother" },
    { es: "Abuelo", en: "Grandfather" },
    { es: "Hermano", en: "Brother" },
    { es: "Hermana", en: "Sister" },
    { es: "Hijo", en: "Son" },
    { es: "Hija", en: "Daughter" },
    { es: "Tío", en: "Uncle" },
    { es: "Tía", en: "Aunt" },
    { es: "Primo", en: "Cousin (male)" },
    { es: "Prima", en: "Cousin (female)" },
    { es: "Sobrino", en: "Nephew" },
    { es: "Cuñado", en: "Brother-in-law" },
    { es: "Cuñada", en: "Sister-in-law" },
    { es: "Yerno", en: "Son-in-law" },
    { es: "Yerna", en: "Daughter-in-law" }
  ],
  ciudad: [
    { es: "Calle", en: "Street" },
    { es: "Parque", en: "Park" },
    { es: "Museo", en: "Museum" },
    { es: "Restaurante", en: "Restaurant" },
    { es: "Supermercado", en: "Supermarket" },
    { es: "Hospital", en: "Hospital" },
    { es: "Escuela", en: "School" },
    { es: "Cine", en: "Cinema" },
    { es: "Banco", en: "Bank" },
    { es: "Farmacia", en: "Pharmacy" }
  ],
  alimentos: [
    { es: "Pan", en: "Bread" },
    { es: "Leche", en: "Milk" },
    { es: "Agua", en: "Water" },
    { es: "Fruta", en: "Fruit" },
    { es: "Carne", en: "Meat" },
    { es: "Pescado", en: "Fish" },
    { es: "Huevo", en: "Egg" },
    { es: "Arroz", en: "Rice" },
    { es: "Queso", en: "Cheese" },
    { es: "Pollo", en: "Chicken" }
  ],
  aeropuerto: [
    { es: "Avión", en: "Airplane" },
    { es: "Azafata", en: "Flight attendant" },
    { es: "Piloto", en: "Pilot" },
    { es: "El viajero", en: "The traveler" },
    { es: "El pasajero", en: "The passenger" },
    { es: "Maleta", en: "Suitcase" },
    { es: "Neceser", en: "Toiletry bag" },
    { es: "Pasaporte", en: "Passport" },
    { es: "Billete de avión", en: "Airplane ticket" },
    { es: "Tarjeta de avión", en: "Airplane card" },
    { es: "Mochila", en: "Backpack" },
    { es: "Equipaje", en: "Luggage" },
    { es: "Equipaje de mano", en: "Hand luggage" },
    { es: "Bolso de mano", en: "Handbag" },
    { es: "Salidas", en: "Departures" },
    { es: "Cola/ fila", en: "Queue / Line" },
    { es: "El detector de metales", en: "The metal detector" },
    { es: "El guardia de seguridad", en: "The security guard" },
    { es: "La puerta de embarque", en: "The boarding gate" },
    { es: "Tarjeta de embarque", en: "Boarding pass" },
    { es: "Llegadas", en: "Arrivals" },
    { es: "Recogida de equipaje", en: "Baggage claim" },
    { es: "El mostrador", en: "The counter" },
    { es: "La pista de aterrizaje", en: "The runway" },
    { es: "El aterrizaje", en: "The landing" },
    { es: "El despegue", en: "The takeoff" },
    { es: "La torre de control", en: "The control tower" },
    { es: "Cinta de recogida de equipaje", en: "Baggage carousel" },
    { es: "Exceso de equipaje", en: "Excess baggage" },
    { es: "Sala de espera", en: "Waiting room" },
    { es: "Asiento", en: "Seat" },
    { es: "Ventana", en: "Window" },
    { es: "Medio", en: "Middle" },
    { es: "Pasillo", en: "Aisle" },
    { es: "Aeropuerto", en: "Airport" },
    { es: "Puerta de embarque", en: "Boarding gate" },
    { es: "Exceso de equipaje", en: "Extra luggage" },
    { es: "Pasar por seguridad", en: "Go through security" },
    { es: "Llevar", en: "To carry / take" },
    { es: "Embarcar", en: "To board" },
    { es: "Despegar", en: "To take off" },
    { es: "Aterrizar", en: "To land" },
    { es: "Pasar", en: "To pass" },
    { es: "Pesar", en: "To weigh" },
    { es: "Ser", en: "To be (permanent)" },
    { es: "Estar", en: "To be (temporary)" },
    { es: "Volar", en: "To fly" },
    { es: "Viajar", en: "To travel" },
    { es: "El accidente", en: "The accident" }
  ],
  aeropuerto_2: [
    { es: "¿Puede poner las maletas aquí?", en: "Can you put the suitcases here?" },
    { es: "¿Cuántas maletas va a facturar?", en: "How many suitcases are you going to check in?" },
    { es: "¿Es ese su maleta de mano?", en: "Is that your carry-on bag?" },
    { es: "¿Qué asiento quiere? ¿Ventanilla, medio o pasillo?", en: "Which seat do you want? Window, middle or aisle?" },
    { es: "Aquí tiene su billete de avión", en: "Here is your airplane ticket" },
    { es: "La puerta de embarque es…", en: "The boarding gate is..." },
    { es: "Su maleta tiene exceso de equipaje", en: "Your suitcase has excess baggage" },
    { es: "Tiene que pagar", en: "You have to pay" },
    { es: "Su vuelo sale a las 15:00 de la tarde", en: "Your flight leaves at 3:00 PM" },
    { es: "¡Qué tenga un buen viaje!", en: "Have a nice trip!" }
  ],
  the_clothes: [
    { es: "Vestido", en: "Dress" },
    { es: "Blusa", en: "Blouse" },
    { es: "Camisa", en: "Shirt" },
    { es: "Pantalón", en: "Pants" },
    { es: "El bolso", en: "The bag" },
    { es: "Falda", en: "Skirt" },
    { es: "Zapatos", en: "Shoes" },
    { es: "El cinturon", en: "The belt" },
    { es: "Chaqueta", en: "Jacket" },
    { es: "Jersey", en: "Sweater" },
    { es: "Calcetines", en: "Socks" },
    { es: "Gorra", en: "Cap" },
    { es: "Gorro", en: "Beanie / Winter hat" },
    { es: "Bufanda", en: "Scarf" },
    { es: "La corbata", en: "The tie" },
    { es: "Sandalias", en: "Sandals" },
    { es: "Guantes", en: "Gloves" },
    { es: "Sombrero", en: "Hat" },
    { es: "Gafas", en: "Glasses" },
    { es: "Vaqueros", en: "Jeans" },
    { es: "El traje", en: "The suit" },
    { es: "Abrigo", en: "Coat" },
    { es: "Pijama", en: "Pajamas" },
    { es: "Las botas", en: "The boots" },
    { es: "Zapatos deportivos", en: "Sneakers / Sports shoes" },
    { es: "Chándal", en: "Tracksuit" },
    { es: "Chancla", en: "Flip-flop" },
    { es: "Pantalones cortos", en: "Shorts" },
    { es: "Vaqueros cortos", en: "Denim shorts" },
    { es: "Bañador", en: "Swimsuit" },
    { es: "El bikini", en: "The bikini" },
    { es: "Toalla", en: "Towel" },
    { es: "Accesorios", en: "Accessories" },
    { es: "Anillo", en: "Ring" },
    { es: "El reloj", en: "The watch" },
    { es: "Collar", en: "Necklace" },
    { es: "Gafas de sol", en: "Sunglasses" },
    { es: "Pulsera", en: "Bracelet" },
    { es: "Los aretes", en: "The earrings" },
    { es: "Pañuelo", en: "Handkerchief" },
    { es: "El paraguas", en: "The umbrella" },
    { es: "Los tacones", en: "The high heels" },
    { es: "Azúl", en: "Blue" },
    { es: "Rojo", en: "Red" },
    { es: "Amarillo", en: "Yellow" },
    { es: "Verde", en: "Green" },
    { es: "Lila", en: "Lilac" },
    { es: "Naranja", en: "Orange" },
    { es: "Violeta", en: "Violet" },
    { es: "Y", en: "And" },
    { es: "Algodón", en: "Cotton" },
    { es: "Querer", en: "To want" }
  ],
  tienda_de_ropa_conv: [
    { es: "No sé", en: "I don't know" },
    { es: "Talla", en: "Size" },
    { es: "Probar", en: "To try on" },
    { es: "Poder", en: "To be able to / Can" },
    { es: "El vendedor / La vendedora", en: "The salesman / saleswoman" },
    { es: "El cliente / La clienta", en: "The customer" },
    { es: "La tienda", en: "The shop / store" },
    { es: "La tienda de ropa", en: "The clothing store" },
    { es: "El corte inglés", en: "El Corte Inglés (Department store)" },
    { es: "¿En qué puedo ayudarle?", en: "How can I help you?" },
    { es: "¿Qué desea?", en: "What would you like?" },
    { es: "¿De qué color?", en: "What color?" },
    { es: "¿De qué talla?", en: "What size?" },
    { es: "¿De qué precio?", en: "What price?" },
    { es: "¿De qué material?", en: "What material?" },
    { es: "¿De qué tamaño?", en: "What size? (dimension)" },
    { es: "¿Qué talla tiene?", en: "What size do you take?" },
    { es: "Yo quiero una camisa negra", en: "I want a black shirt" },
    { es: "Yo quiero una falda a rayas", en: "I want a striped skirt" },
    { es: "A rayas", en: "Striped" },
    { es: "Yo quiero una bufanda", en: "I want a scarf" },
    { es: "De color rojo", en: "Red colored" },
    { es: "De la talla 40", en: "Size 40" },
    { es: "De la talla M (eme)", en: "Size M" },
    { es: "Yo quiero una falda cara", en: "I want an expensive skirt" },
    { es: "Yo quiero ropa barata", en: "I want cheap clothes" },
    { es: "Tamaño", en: "Size / Dimension" },
    { es: "Grande", en: "Big" },
    { es: "Pequeño", en: "Small" },
    { es: "Mediano", en: "Medium" },
    { es: "Corto", en: "Short" },
    { es: "Largo", en: "Long" },
    { es: "¿Dónde están los probadores?", en: "Where are the fitting rooms?" },
    { es: "El probador", en: "The fitting room" },
    { es: "¿Dónde puedo probarme la ropa?", en: "Where can I try on the clothes?" },
    { es: "¿Dónde está la caja?", en: "Where is the checkout?" },
    { es: "La caja", en: "The checkout / cash register" },
    { es: "¿Cómo lo quiere?", en: "How do you want it?" },
    { es: "De algodón", en: "Made of cotton" },
    { es: "De lana", en: "Made of wool" },
    { es: "De cuero", en: "Made of leather" },
    { es: "Tenemos estos modelos", en: "We have these models" },
    { es: "Al fondo", en: "At the back" },
    { es: "Quedar", en: "To fit / To suit" },
    { es: "¿Le gusta alguno?", en: "Do you like any?" },
    { es: "El probador está a su mano izquierda", en: "The fitting room is on your left" },
    { es: "¿Qué tal le queda?", en: "How does it fit you?" },
    { es: "¿Cómo le queda?", en: "How does it fit you?" },
    { es: "Me queda muy bien", en: "It fits me very well" },
    { es: "Me gusta mucho", en: "I like it a lot" },
    { es: "¿Cuánto cuesta?", en: "How much does it cost?" },
    { es: "Está muy caro", en: "It's very expensive" },
    { es: "Está muy barato", en: "It's very cheap" },
    { es: "Está muy bonito", en: "It's very pretty" },
    { es: "Está muy feo", en: "It's very ugly" },
    { es: "No me queda bien", en: "It doesn't fit me well" },
    { es: "Caro", en: "Expensive" },
    { es: "Bonito", en: "Pretty / Nice" },
    { es: "Feo", en: "Ugly" },
    { es: "Barato", en: "Cheap" },
    { es: "No me queda bien ", en: "It doesn't fit me well (alt)" },
    { es: "No, no lo quiero", en: "No, I don't want it" },
    { es: "De acuerdo, me lo llevo", en: "Okay, I'll take it" },
    { es: "Muy bien, pase por caja", en: "Very well, go to the checkout" },
    { es: "El vestido cuesta 50 euros", en: "The dress costs 50 euros" },
    { es: "Los zapatos cuestan 50 euros", en: "The shoes cost 50 euros" },
    { es: "¡Qué tenga un buen día!", en: "Have a nice day!" }
  ],
  illness: [
    { es: "Náuseas", en: "Nausea" },
    { es: "Vómito", en: "Vomiting" },
    { es: "Diarrea", en: "Diarrhea" },
    { es: "Fiebre", en: "Fever" },
    { es: "Fatiga inusual", en: "Unusual fatigue" },
    { es: "Picor", en: "Itching" },
    { es: "Dolor de cabeza", en: "Headache" },
    { es: "Dolor de espalda", en: "Back pain" },
    { es: "Dolor articular", en: "Joint pain" },
    { es: "Calambres", en: "Cramps" },
    { es: "Mareo", en: "Dizziness" },
    { es: "Nerviosismo", en: "Nervousness" },
    { es: "Trastorno del sueño", en: "Sleep disorder" },
    { es: "Contracciones", en: "Contractions" },
    { es: "Problemas circulatorios", en: "Circulatory problems" },
    { es: "Ardor de estómago", en: "Heartburn" },
    { es: "Estreñimiento", en: "Constipation" },
    { es: "Dolor de estómago", en: "Stomach ache" },
    { es: "Catarro", en: "Cold / Catarrh" },
    { es: "Tos", en: "Cough" },
    { es: "Bronquitis", en: "Bronchitis" },
    { es: "Pérdida auditiva", en: "Hearing loss" },
    { es: "Gripe", en: "Flu" },
    { es: "Resfriado", en: "Common cold" },
    { es: "Alergia", en: "Allergy" },
    { es: "Infección", en: "Infection" },
    { es: "Inflamación", en: "Inflammation" },
    { es: "Erupción", en: "Rash" },
    { es: "Escalofríos", en: "Chills" },
    { es: "Dolor de garganta", en: "Sore throat" },
    { es: "Desmayo", en: "Fainting" },
    { es: "Hinchazón", en: "Swelling" },
    { es: "Moretón", en: "Bruise" },
    { es: "Herida", en: "Wound" },
    { es: "Cicatriz", en: "Scar" }
  ],
  first_aid: [
    { es: "Medicamento", en: "Medicine" },
    { es: "Medicamento con receta obligatoria", en: "Prescription medicine" },
    { es: "Kit de primeros auxilios", en: "First aid kit" },
    { es: "Esparadrapo", en: "Adhesive tape / Plaster" },
    { es: "Jeringa", en: "Syringe" },
    { es: "Aguja", en: "Needle" },
    { es: "Primeros auxilios", en: "First aid" },
    { es: "Respiración boca a boca", en: "Mouth-to-mouth resuscitation" },
    { es: "Reanimación", en: "Resuscitation" },
    { es: "Posición de seguridad", en: "Recovery position" },
    { es: "Víctima", en: "Victim" },
    { es: "Masaje cardíaco", en: "Cardiac massage / CPR" },
    { es: "Máscara de oxígeno", en: "Oxygen mask" },
    { es: "Hemorragia nasal", en: "Nosebleed" },
    { es: "Botella de agua caliente", en: "Hot water bottle" },
    { es: "Lesión", en: "Injury" },
    { es: "Herida", en: "Wound" },
    { es: "Accidente", en: "Accident" },
    { es: "Inconsciente", en: "Unconscious" },
    { es: "Shock", en: "Shock" },
    { es: "Gritar", en: "To shout / scream" },
    { es: "Sangre", en: "Blood" },
    { es: "Quemadura", en: "Burn" },
    { es: "Envenenamiento", en: "Poisoning" },
    { es: "Picadura", en: "Sting / Bite (insect)" },
    { es: "Corte", en: "Cut" },
    { es: "Mordida", en: "Bite" },
    { es: "Ahogarse", en: "To drown / choke" },
    { es: "Moretón", en: "Bruise" },
    { es: "Vendaje", en: "Bandage" },
    { es: "Ambulancia", en: "Ambulance" },
    { es: "Hospital", en: "Hospital" },
    { es: "Médico", en: "Doctor" },
    { es: "Enfermero", en: "Nurse" },
    { es: "Termómetro", en: "Thermometer" },
    { es: "Alcohol", en: "Alcohol" },
    { es: "Algodón", en: "Cotton" },
    { es: "Gasa", en: "Gauze" },
    { es: "Pinzas", en: "Tweezers" },
    { es: "Tijeras", en: "Scissors" },
    { es: "Guantes", en: "Gloves" },
    { es: "Desinfectante", en: "Disinfectant" },
    { es: "Pomada", en: "Ointment" },
    { es: "Pastilla", en: "Pill" },
    { es: "Jarabe", en: "Syrup" }
  ],
  hospital: [
    { es: "El pediatra", en: "The pediatrician" },
    { es: "El ginecólogo", en: "The gynecologist" },
    { es: "El fisioterapeuta", en: "The physiotherapist" },
    { es: "El consultorio", en: "The doctor's office" },
    { es: "El auxiliar médico", en: "The medical assistant" },
    { es: "La consulta médica", en: "The medical consultation" },
    { es: "El laboratorio", en: "The laboratory" },
    { es: "El doctor o la doctora", en: "The doctor" },
    { es: "La camilla", en: "The stretcher" },
    { es: "La radiografía", en: "The X-ray" },
    { es: "Extraer una muestra de sangre", en: "To take a blood sample" },
    { es: "La receta médica", en: "The medical prescription" },
    { es: "La hora", en: "The time / hour" },
    { es: "La cita", en: "The appointment" },
    { es: "La hora de visita", en: "The visiting hour" },
    { es: "La compañía de seguros médicos", en: "The health insurance company" },
    { es: "Ponerle a alguien una inyección", en: "To give someone an injection" },
    { es: "La inyección", en: "The injection" },
    { es: "El diagnóstico", en: "The diagnosis" },
    { es: "El tratamiento", en: "The treatment" },
    { es: "Los resultados", en: "The results" },
    { es: "La sala de espera", en: "The waiting room" },
    { es: "El quirófano", en: "The operating room" },
    { es: "La enfermera / El enfermero", en: "The nurse" },
    { es: "El paciente", en: "The patient" },
    { es: "La farmacia", en: "The pharmacy" },
    { es: "La ambulancia", en: "The ambulance" },
    { es: "El estetoscopio", en: "The stethoscope" },
    { es: "La presión arterial", en: "The blood pressure" },
    { es: "El termómetro", en: "The thermometer" }
  ],
  human_organs: [
    { es: "El cerebro", en: "The brain" },
    { es: "El corazón", en: "The heart" },
    { es: "La glándula tiroides", en: "The thyroid gland" },
    { es: "El riñón", en: "The kidney" },
    { es: "El nervio", en: "The nerve" },
    { es: "Los pulmones", en: "The lungs" },
    { es: "La tráquea", en: "The trachea" },
    { es: "La válvula cardíaca", en: "The heart valve" },
    { es: "Los bronquios", en: "The bronchi" },
    { es: "El diafragma", en: "The diaphragm" },
    { es: "El esófago", en: "The esophagus" },
    { es: "El hígado", en: "The liver" },
    { es: "El estómago", en: "The stomach" },
    { es: "El intestino grueso", en: "The large intestine" },
    { es: "El intestino delgado", en: "The small intestine" },
    { es: "Músculos", en: "Muscles" },
    { es: "Abdominales", en: "Abdominals" },
    { es: "Bíceps", en: "Biceps" },
    { es: "Tríceps", en: "Triceps" },
    { es: "Gemelos", en: "Calves" },
    { es: "Cuádriceps", en: "Quadriceps" },
    { es: "Pectoral", en: "Pectoral" },
    { es: "Ligamento de la corva", en: "Hamstring" },
    { es: "Tendón de Aquiles", en: "Achilles tendon" },
    { es: "Huesos", en: "Bones" },
    { es: "Cráneo", en: "Skull" },
    { es: "Mandíbula", en: "Jaw" },
    { es: "Clavícula", en: "Collarbone" },
    { es: "Caja torácica", en: "Rib cage" },
    { es: "Costillas", en: "Ribs" },
    { es: "Húmero", en: "Humerus" },
    { es: "Fémur", en: "Femur" },
    { es: "Pelvis", en: "Pelvis" },
    { es: "Vértebras lumbares", en: "Lumbar vertebrae" },
    { es: "Cócsix", en: "Coccyx" },
    { es: "Rótula", en: "Kneecap" },
    { es: "Esternón", en: "Sternum" },
    { es: "Ligamento", en: "Ligament" },
    { es: "Cartílago", en: "Cartilage" },
    { es: "Ligamento cruzado", en: "Cruciate ligament" }
  ],
  cuerpo_humano: [
    { es: "La cabeza", en: "The head" },
    { es: "Los brazos", en: "The arms" },
    { es: "Las piernas", en: "The legs" },
    { es: "Los pies", en: "The feet" },
    { es: "La cara", en: "The face" },
    { es: "La nariz", en: "The nose" },
    { es: "La boca", en: "The mouth" },
    { es: "El oído", en: "The inner ear" },
    { es: "Las orejas", en: "The ears" },
    { es: "Las cejas", en: "The eyebrows" },
    { es: "Las pestañas", en: "The eyelashes" },
    { es: "El pelo", en: "The hair" },
    { es: "La frente", en: "The forehead" },
    { es: "Los labios", en: "The lips" },
    { es: "La lengua", en: "The tongue" },
    { es: "La barbilla", en: "The chin" },
    { es: "Los dientes", en: "The teeth" },
    { es: "Las muelas", en: "The molars" },
    { es: "Las mejillas", en: "The cheeks" },
    { es: "La nuca", en: "The back of the neck" },
    { es: "La garganta", en: "The throat" },
    { es: "El hombro", en: "The shoulder" },
    { es: "El codo", en: "The elbow" },
    { es: "La mano", en: "The hand" },
    { es: "La muñeca", en: "The wrist" },
    { es: "Los dedos", en: "The fingers" },
    { es: "Las uñas", en: "The nails" },
    { es: "El pecho", en: "The chest" },
    { es: "Las caderas", en: "The hips" },
    { es: "El estómago", en: "The stomach" },
    { es: "Los pechos", en: "The breasts" },
    { es: "La espalda", en: "The back" },
    { es: "La barriga", en: "The belly" },
    { es: "La barba", en: "The beard" },
    { es: "El bigote", en: "The mustache" }
  ],
  sentences_to_be: [
    { es: "Yo soy María", en: "I am María" },
    { es: "Tú eres mi amigo", en: "You are my friend" },
    { es: "Él es mi padre", en: "He is my father" },
    { es: "Ella es mi madre", en: "She is my mother" },
    { es: "Usted es mi abuelo", en: "You (formal) are my grandfather" },
    { es: "Nosotros somos Carlos y María", en: "We are Carlos and María" },
    { es: "Vosotros sois holandeses", en: "You all (Spain) are Dutch" },
    { es: "Ellos son policía", en: "They are police officers" },
    { es: "Ustedes son chilenos", en: "You all (L.Am) are Chilean" },
    { es: "Nosotras somos María y Antonia", en: "We (f) are María and Antonia" },
    { es: "Vosotras sois Luisa y Clara", en: "You all (Spain/f) are Luisa y Clara" },
    { es: "Ellas son mis tías", en: "They (f) are my aunts" },
    { es: "Yo soy tu amiga", en: "I am your friend (f)" },
    { es: "Tú eres maestro", en: "You are a teacher" },
    { es: "Él es de Madrid", en: "He is from Madrid" },
    { es: "Ella es cocinera", en: "She is a cook" },
    { es: "Nosotros somos novios", en: "We are a couple (fiancés/sweethearts)" },
    { es: "Ellos son trabajadores", en: "They are workers" },
    { es: "Ustedes son de Venezuela", en: "You all (L.Am) are from Venezuela" },
    { es: "La chica es guapa", en: "The girl is pretty" },
    { es: "Amsterdam es la capital de Holanda", en: "Amsterdam is the capital of Holland" },
    { es: "Yo soy inteligente", en: "I am intelligent" }
  ],
  ciudad_description: [
    { es: "Hay", en: "There is / There are" },
    { es: "¿Hay una farmacia por aquí?", en: "Is there a pharmacy around here?" },
    { es: "Ciudad", en: "City" },
    { es: "Pueblo", en: "Town" },
    { es: "En", en: "In / On / At" },
    { es: "¿Hay una piscina?", en: "Is there a swimming pool?" },
    { es: "Sí, sí hay", en: "Yes, there is / there are" },
    { es: "No, no hay", en: "No, there isn't / there aren't" },
    { es: "¿Hay un museo?", en: "Is there a museum?" },
    { es: "¿Hay una biblioteca?", en: "Is there a library?" },
    { es: "¿Hay una discoteca?", en: "Is there a nightclub?" },
    { es: "¿Hay una estación de trenes?", en: "Is there a train station?" },
    { es: "¿Hay un centro comercial?", en: "Is there a shopping center?" },
    { es: "¿Hay un lugar famoso?", en: "Is there a famous place?" },
    { es: "¿Hay playas?", en: "Are there beaches?" },
    { es: "Un", en: "A / An (masculine singular)" },
    { es: "En la ciudad", en: "In the city" },
    { es: "¿Cómo es tu ciudad?", en: "What is your city like?" },
    { es: "Preguntas", en: "Questions" },
    { es: "¿Qué hay en tu ciudad?", en: "What is in your city? / What's in your town?" },
    { es: "¿Hay una playa?", en: "Is there a beach?" },
    { es: "¿Te gusta la ciudad?", en: "Do you like the city?" },
    { es: "Allí", en: "There" },
    { es: "Aquí", en: "Here" },
    { es: "Lejos", en: "Far" },
    { es: "Cerca", en: "Near / Close" },
    { es: "También", en: "Also / Too" },
    { es: "Además", en: "Furthermore / Besides" },
    { es: "Pero", en: "But" },
    { es: "Mucho", en: "A lot / Much" },
    { es: "Poco", en: "Little / Few" },
    { es: "No me gusta", en: "I don't like" },
    { es: "Típico", en: "Typical" },
    { es: "Norte", en: "North" },
    { es: "Sur", en: "South" },
    { es: "Este", en: "East" },
    { es: "Oeste", en: "West" },
    { es: "Es un pueblo histórico", en: "It's a historic town" },
    { es: "Es pequeño", en: "It's small" },
    { es: "Es grande", en: "It's big" },
    { es: "Es muy bonito", en: "It's very beautiful" },
    { es: "Hay un supermercado", en: "There is a supermarket" },
    { es: "Hay un colegio", en: "There is a school" },
    { es: "Hay mucha naturaleza", en: "There is a lot of nature" },
    { es: "No hay universidades", en: "There are no universities" },
    { es: "No hay edificios modernos", en: "There are no modern buildings" },
    { es: "No hay oficina de correos", en: "There is no post office" }
  ],
  ciudad_2_description: [
    { es: "Hay", en: "There is / There are" },
    { es: "¿Hay una farmacia por aquí?", en: "Is there a pharmacy around here?" },
    { es: "Ciudad", en: "City" },
    { es: "Pueblo", en: "Town" },
    { es: "En", en: "In / On / At" },
    { es: "¿Hay una piscina?", en: "Is there a swimming pool?" },
    { es: "Sí, sí hay", en: "Yes, there is / there are" },
    { es: "No, no hay", en: "No, there isn't / there aren't" }, 
    { es: "¿Hay un museo?", en: "Is there a museum?" },
    { es: "¿Hay una biblioteca?", en: "Is there a library?" }, 
    { es: "¿Hay una discoteca?", en: "Is there a nightclub?" }, 
    { es: "¿Hay una estación de trenes?", en: "Is there a train station?" }, 
    { es: "¿Hay un centro comercial?", en: "Is there a shopping center?" }, 
    { es: "¿Hay un lugar famoso?", en: "Is there a famous place?" }, 
    { es: "¿Hay playas?", en: "Are there beaches?" }, 
    { es: "Un", en: "A / An (masculine singular)" },
    { es: "En la ciudad", en: "In the city" },
    { es: "¿Cómo es tu ciudad?", en: "What is your city like?" },
    { es: "Preguntas", en: "Questions" },
    { es: "¿Qué hay en tu ciudad?", en: "What is in your city? / What's in your town?" },
    { es: "¿Hay una playa?", en: "Is there a beach?" },
    { es: "¿Te gusta la ciudad?", en: "Do you like the city?" },
    { es: "Allí", en: "There (over there)" },
    { es: "Aquí", en: "Here" },
    { es: "Lejos", en: "Far" },
    { es: "Cerca", en: "Near / Close" },
    { es: "También", en: "Also / Too" },
    { es: "Además", en: "Furthermore / Besides" },
    { es: "Pero", en: "But" },
    { es: "Mucho", en: "A lot / Much" },
    { es: "Poco", en: "Little / Few" },
    { es: "No me gusta", en: "I don't like" },
    { es: "Típico", en: "Typical" },
    { es: "Norte", en: "North" },
    { es: "Sur", en: "South" },
    { es: "Este", en: "East" },
    { es: "Oeste", en: "West" },
    { es: "Es un pueblo histórico", en: "It's a historic town" }
  ],
  ciudad_3_words: [
    { es: "No entiendo", en: "I don't understand" },
    { es: "¿Puede repetirlo, por favor?", en: "Can you repeat that, please?" },
    { es: "¿Qué significa eso?", en: "What does that mean?" },
    { es: "¿Cómo se escribe…?", en: "How do you write…?" },
    { es: "¿Cómo se pronuncia?", en: "How is it pronounced?" },
    { es: "¿Puede hablar más despacio?", en: "Can you speak slower?" },
    { es: "Gracias", en: "Thank you" },
    { es: "De nada", en: "You're welcome" },
    { es: "Tengo una pregunta", en: "I have a question" },
    { es: "No lo sé", en: "I don't know" },
    { es: "¿Cómo se deletrea tu…?", en: "How do you spell your…?" },
    { es: "¿Por qué?", en: "Why?" },
    { es: "Piscina", en: "Swimming pool" },
    { es: "Lugar", en: "Place" },
    { es: "Famoso", en: "Famous" },
    { es: "Lugar famoso", en: "Famous place" },
    { es: "Playas", en: "Beaches" },
    { es: "Tienda", en: "Store / Shop" },
    { es: "Tienda de ropa", en: "Clothing store" },
    { es: "Estadio", en: "Stadium" },
    { es: "Puente", en: "Bridge" },
    { es: "Iglesia", en: "Church" },
    { es: "Río", en: "River" },
    { es: "Lago", en: "Lake" },
    { es: "Grande", en: "Big / Large" },
    { es: "Pequeño", en: "Small" },
    { es: "Bonito", en: "Beautiful / Pretty" },
    { es: "Moderno", en: "Modern" },
    { es: "Antiguo", en: "Old / Ancient" },
    { es: "Ruidoso", en: "Noisy" },
    { es: "¿Qué?", en: "What?" },
    { es: "¿Cómo?", en: "How?" }
  ],
  estar_sentences: [
    { es: "Yo estoy en Madrid", en: "I am in Madrid" },
    { es: "Tú estás en el centro", en: "You are downtown" },
    { es: "Él/ella/usted está en el hospital", en: "He/she/you (formal) is/are in the hospital" },
    { es: "Nosotros estamos felices", en: "We are happy" },
    { es: "Vosotros estáis triste", en: "You all (Spain) are sad" },
    { es: "Ustedes están aquí", en: "You all (Latin America) are here" },
    { es: "Ellos están en casa", en: "They are at home" },
    { es: "El agua está fría", en: "The water is cold" },
    { es: "El café está caliente", en: "The coffee is hot" },
    { es: "La ropa está sucia", en: "The clothes are dirty" },
    { es: "Nosotros estamos casados", en: "We are married" }
  ],
  giving_directions: [
    { es: "Girar", en: "To turn" },
    { es: "Cruzar", en: "To cross" },
    { es: "Seguir", en: "To follow / To continue" },
    { es: "Pasar", en: "To pass / To go by" },
    { es: "La calle", en: "The street" },
    { es: "La primera", en: "The first" },
    { es: "La segunda", en: "The second" },
    { es: "La tercera", en: "The third" },
    { es: "La cuarta", en: "The fourth" },
    { es: "A la izquierda", en: "To the left / On the left" },
    { es: "A la derecha", en: "To the right / On the right" },
    { es: "Todo recto", en: "Straight ahead" },
    { es: "¿Está lejos?", en: "Is it far?" },
    { es: "¿Está cerca?", en: "Is it close / near?" },
    { es: "Tener que…", en: "To have to…" },
    { es: "Tiene que seguir todo recto", en: "You have to go straight ahead" },
    { es: "Tiene que girar a la izquierda", en: "You have to turn left" },
    { es: "Al final de la calle", en: "At the end of the street" },
    { es: "Cruce", en: "Intersection" },
    { es: "A pie", en: "On foot" },
    { es: "La avenida", en: "The avenue" },
    { es: "La plaza", en: "The square" },
    { es: "¿Dónde está la calle Madrid?", en: "Where is Madrid street?" },
    { es: "¿Para llegar a la estación?", en: "To get to the station?" },
    { es: "¿Hay una farmacia por aquí?", en: "Is there a pharmacy around here?" },
    { es: "¿Dónde está el centro?", en: "Where is the center / downtown?" },
    { es: "¿Para ir al hotel Barcelona?", en: "To go to the Barcelona hotel?" },
    { es: "Tiene que girar a la derecha", en: "You have to turn right" },
    { es: "Tiene que girar a la izquierda", en: "You have to turn left" },
    { es: "Tiene que ir a pie", en: "You have to go on foot" },
    { es: "Siga todo recto, gire a la derecha en la segunda calle a la izquierda.", en: "Go straight, turn right on the second street on the left." }
  ],
  restaurant_words_1: [
    { es: "https://images.unsplash.com/photo-1517248135467-4c7ed7b96e06?auto=format&fit=crop&q=80&w=2070&seed=restaurant", en: "Restaurant" },
    { es: "https://images.unsplash.com/photo-1549591463-c7e6c4e0f0b4?auto=format&fit=crop&q=80&w=1974&seed=pitcher", en: "Water pitcher" },
    { es: "https://images.unsplash.com/photo-1627447470404-517c5b2a0c6a?auto=format&fit=crop&q=80&w=2070&seed=wineglass", en: "Wine glass" },
    { es: "https://images.unsplash.com/photo-1595183492770-5d6664e43b67?auto=format&fit=crop&q=80&w=1974&seed=glass", en: "Drinking glass" },
    { es: "https://images.unsplash.com/photo-1561048841-86a074c7604a?auto=format&fit=crop&q=80&w=2070&seed=cup", en: "Cup" },
    { es: "https://images.unsplash.com/photo-1628102491629-9e79435b8007?auto=format&fit=crop&q=80&w=1974&seed=salt", en: "Salt" },
    { es: "https://images.unsplash.com/photo-1628102491629-9e79435b8007?auto=format&fit=crop&q=80&w=1974&seed=pepper", en: "Pepper" },
    { es: "https://images.unsplash.com/photo-1594950965747-0639e44d320b?auto=format&fit=crop&q=80&w=2070&seed=sugar", en: "Sugar" },
    { es: "https://images.unsplash.com/photo-1546422340-9a3c0f4f0c97?auto=format&fit=crop&q=80&w=1974&seed=fork", en: "Fork" },
    { es: "https://images.unsplash.com/photo-1598490076048-5c4d0b1d0a5f?auto=format&fit=crop&q=80&w=1974&seed=spoon", en: "Spoon" },
    { es: "https://images.unsplash.com/photo-1598490076048-5c4d0b1d0a5f?auto=format&fit=crop&q=80&w=1974&seed=teaspoon", en: "Teaspoon" },
    { es: "https://images.unsplash.com/photo-1546422340-9a3c0f4f0c97?auto=format&fit=crop&q=80&w=1974&seed=knife", en: "Knife" },
    { es: "https://images.unsplash.com/photo-1563821045059-e24c2ed2c503?auto=format&fit=crop&q=80&w=2070&seed=napkin", en: "Napkin" },
    { es: "https://images.unsplash.com/photo-1582239414264-a3f12d5b6a7a?auto=format&fit=crop&q=80&w=2070&seed=tablecloth", en: "Tablecloth" },
    { es: "https://images.unsplash.com/photo-1604908077420-a61f52d0b5d9?auto=format&fit=crop&q=80&w=1974&seed=plate", en: "Plate" },
    { es: "https://images.unsplash.com/photo-1604908077420-a61f52d0b5d9?auto=format&fit=crop&q=80&w=1974&seed=bowl", en: "Deep plate" },
    { es: "https://images.unsplash.com/photo-1604908077420-a61f52d0b5d9?auto=format&fit=crop&q=80&w=1974&seed=flatplate", en: "Flat plate" },
    { es: "https://images.unsplash.com/photo-1517248135467-4c7ed7b96e06?auto=format&fit=crop&q=80&w=2070&seed=table", en: "Table" },
    { es: "https://images.unsplash.com/photo-1549241521-e0e67610014b?auto=format&fit=crop&q=80&w=2070&seed=bill", en: "The bill" },
    { es: "https://images.unsplash.com/photo-1555558913-71822c95ec1a?auto=format&fit=crop&q=80&w=2070&seed=bonappetit", en: "Enjoy your meal" },
    { es: "https://images.unsplash.com/photo-1605716173259-2c0a9e7f7b7f?auto=format&fit=crop&q=80&w=1974&seed=tip", en: "The tip" },
  ],
  restaurant_words_matching: [
    { es: "Restaurante", en: "Restaurant" },
    { es: "La jarra de agua", en: "Water pitcher" },
    { es: "La copa", en: "Wine glass" },
    { es: "El vaso", en: "Drinking glass" },
    { es: "La taza", en: "Cup" },
    { es: "El tenedor", en: "Fork" },
    { es: "La cuchara", en: "Spoon" },
    { es: "El cuchillo", en: "Knife" },
    { es: "La servilleta", en: "Napkin" },
    { es: "El plato", en: "Plate" },
  ],
  restaurant_quiz_3: [
    { es: "Buenas tardes, ¿Ha reservado?", en: "Good afternoon, have you booked?" },
    { es: "¿Qué desea?", en: "What would you like?" },
    { es: "El plato del día es", en: "The dish of the day is" },
    { es: "¿Cómo quiere la carne? Bien hecha, poco hecha o en su punto?", en: "How do you want the meat? Well done, rare, or medium?" },
    { es: "¿Ha elegido ya?", en: "Have you chosen yet?" },
    { es: "De primero tenemos", en: "For starters we have" },
    { es: "De segundo tenemos", en: "For the main course we have" },
    { es: "De postre tenemos", en: "For dessert we have" },
    { es: "El cliente", en: "The client" },
    { es: "Para mi un/ una", en: "For me a" },
    { es: "De primero quiero….", en: "For starters I want..." },
    { es: "De segundo quiero…", en: "For the main course I want..." },
    { es: "De postre quiero…", en: "For dessert I want..." },
    { es: "Para beber quiero…", en: "To drink I want..." },
    { es: "Para comer quiero…", en: "To eat I want..." },
    { es: "¿Qué lleva el pollo?", en: "What's in the chicken?" },
    { es: "¿Me trae la cuenta, por favor?", en: "Can you bring me the bill, please?" },
    { es: "¿Qué es?", en: "What is it?" },
    { es: "No me gusta la comida", en: "I don't like the food" },
    { es: "¿Me puede traer…?", en: "Can you bring me...?" },
    { es: "Las patatas están muy saladas", en: "The potatoes are very salty" },
    { es: "La sopa no tiene sal", en: "The soup has no salt" },
    { es: "La comida está fría", en: "The food is cold" }
  ],
  the_food: [
    { es: "Los alimentos", en: "The food", img: getImageUrl("food", 1) },
    { es: "Desayuno", en: "Breakfast", img: getImageUrl("breakfast", 2) },
    { es: "Pan", en: "Bread", img: getImageUrl("bread", 3) },
    { es: "Huevos", en: "Eggs", img: getImageUrl("eggs", 4) },
    { es: "Queso", en: "Cheese", img: getImageUrl("cheese", 5) },
    { es: "Jamón", en: "Ham", img: getImageUrl("ham", 6) },
    { es: "Mantequilla", en: "Butter", img: getImageUrl("butter", 7) },
    { es: "Miel", en: "Honey", img: getImageUrl("honey", 8) },
    { es: "Mermelada", en: "Jam", img: getImageUrl("jam", 9) },
    { es: "Cereales", en: "Cereal", img: getImageUrl("cereal", 10) },
    { es: "Agua", en: "Water", img: getImageUrl("water", 11) },
    { es: "Zumo", en: "Juice", img: getImageUrl("juice", 12) },
    { es: "Leche", en: "Milk", img: getImageUrl("milk", 13) },
    { es: "Café", en: "Coffee", img: getImageUrl("coffee", 14) },
    { es: "Té", en: "Tea", img: getImageUrl("tea", 15) },
    { es: "Almuerzo", en: "Lunch", img: getImageUrl("lunch", 16) },
    { es: "Sopa", en: "Soup", img: getImageUrl("soup", 17) },
    { es: "Ensalada", en: "Salad", img: getImageUrl("salad", 18) },
    { es: "Arroz", en: "Rice", img: getImageUrl("rice", 19) },
    { es: "Pasta", en: "Pasta", img: getImageUrl("pasta", 20) },
    { es: "Carne", en: "Meat", img: getImageUrl("meat", 21) },
    { es: "Pollo", en: "Chicken", img: getImageUrl("chicken", 22) },
    { es: "Pescado", en: "Fish", img: getImageUrl("fish", 23) },
    { es: "Verduras", en: "Vegetables", img: getImageUrl("vegetables", 24) },
    { es: "Patatas", en: "Potatoes", img: getImageUrl("potatoes", 25) },
    { es: "Fruta", en: "Fruit", img: getImageUrl("fruit", 26) },
    { es: "Manzana", en: "Apple", img: getImageUrl("apple", 27) },
    { es: "Plátano", en: "Banana", img: getImageUrl("banana", 28) },
    { es: "Naranja", en: "Orange", img: getImageUrl("orange", 29) },
    { es: "Uvas", en: "Grapes", img: getImageUrl("grapes", 30) },
    { es: "Fresa", en: "Strawberry", img: getImageUrl("strawberry", 31) },
    { es: "Postre", en: "Dessert", img: getImageUrl("dessert", 32) },
    { es: "Helado", en: "Ice cream", img: getImageUrl("icecream", 33) },
    { es: "Pastel", en: "Cake", img: getImageUrl("cake", 34) },
    { es: "Galleta", en: "Cookie", img: getImageUrl("cookie", 35) },
    { es: "Chocolate", en: "Chocolate", img: getImageUrl("chocolate", 36) },
    { es: "Cena", en: "Dinner", img: getImageUrl("dinner", 37) },
    { es: "Pizza", en: "Pizza", img: getImageUrl("pizza", 38) },
    { es: "Hamburguesa", en: "Hamburger", img: getImageUrl("hamburger", 39) },
    { es: "Bocadillo", en: "Sandwich", img: getImageUrl("sandwich", 40) },
    { es: "Vino", en: "Wine", img: getImageUrl("wine", 41) },
    { es: "Cerveza", en: "Beer", img: getImageUrl("beer", 42) },
    { es: "Refresco", en: "Soft drink", img: getImageUrl("softdrink", 43) },
    { es: "Sal", en: "Salt", img: getImageUrl("salt", 44) },
    { es: "Pimienta", en: "Pepper", img: getImageUrl("pepper", 45) },
    { es: "Aceite", en: "Oil", img: getImageUrl("oil", 46) },
    { es: "Vinagre", en: "Vinegar", img: getImageUrl("vinegar", 47) },
    { es: "Azúcar", en: "Sugar", img: getImageUrl("sugar", 48) },
    { es: "Mesa", en: "Table", img: getImageUrl("table", 49) },
    { es: "Silla", en: "Chair", img: getImageUrl("chair", 50) },
    { es: "Plato", en: "Plate", img: getImageUrl("plate", 51) },
    { es: "Vaso", en: "Glass", img: getImageUrl("glass", 52) },
    { es: "Taza", en: "Cup", img: getImageUrl("cup", 53) },
    { es: "Tenedor", en: "Fork", img: getImageUrl("fork", 54) },
    { es: "Cuchillo", en: "Knife", img: getImageUrl("knife", 55) },
    { es: "Cuchara", en: "Spoon", img: getImageUrl("spoon", 56) },
    { es: "Servilleta", en: "Napkin", img: getImageUrl("napkin", 57) },
    { es: "Menú", en: "Menu", img: getImageUrl("menu", 58) },
    { es: "Camarero", en: "Waiter", img: getImageUrl("waiter", 59) },
    { es: "Camarera", en: "Waitress", img: getImageUrl("waitress", 60) },
    { es: "La cuenta", en: "The bill", img: getImageUrl("bill", 61) },
    { es: "Desayunar", en: "To have breakfast", img: getImageUrl("eatingbreakfast", 62) },
    { es: "Almorzar", en: "To have lunch", img: getImageUrl("eatinglunch", 63) },
    { es: "Cenar", en: "To have dinner", img: getImageUrl("eatingdinner", 64) },
    { es: "Comer", en: "To eat", img: getImageUrl("eating", 65) },
    { es: "Beber", en: "To drink", img: getImageUrl("drinking", 66) },
    { es: "Pedir", en: "To order", img: getImageUrl("ordering", 67) },
    { es: "Pagar", en: "To pay", img: getImageUrl("paying", 68) },
    { es: "Propina", en: "Tip", img: getImageUrl("tip", 69) },
    { es: "Delicioso", en: "Delicious", img: getImageUrl("deliciousfood", 70) }
  ],
};

export const NUMBER_DATA = {
  all: [
    { val: 1, es: "uno" },
    { val: 2, es: "dos" },
    { val: 3, es: "tres" },
    { val: 4, es: "cuatro" },
    { val: 5, es: "cinco" },
    { val: 6, es: "seis" },
    { val: 7, es: "siete" },
    { val: 8, es: "ocho" },
    { val: 9, es: "nueve" },
    { val: 10, es: "diez" },
    { val: 11, es: "once" },
    { val: 12, es: "doce" },
    { val: 13, es: "trece" },
    { val: 14, es: "catorce" },
    { val: 15, es: "quince" },
    { val: 16, es: "dieciséis" },
    { val: 17, es: "diecisiete" },
    { val: 18, es: "dieciocho" },
    { val: 19, es: "diecinueve" },
    { val: 20, es: "veinte" },
    { val: 21, es: "veintiuno" },
    { val: 22, es: "veintidós" },
    { val: 23, es: "veintitrés" },
    { val: 24, es: "veinticuatro" },
    { val: 25, es: "veinticinco" },
    { val: 26, es: "veintiséis" },
    { val: 27, es: "veintisiete" },
    { val: 28, es: "veintiocho" },
    { val: 29, es: "veintinueve" },
    { val: 30, es: "treinta" },
    { val: 31, es: "treinta y uno" },
    { val: 32, es: "treinta y dos" },
    { val: 33, es: "treinta y tres" },
    { val: 34, es: "treinta y cuatro" },
    { val: 35, es: "treinta y cinco" },
    { val: 36, es: "treinta y seis" },
    { val: 37, es: "treinta y siete" },
    { val: 38, es: "treinta y ocho" },
    { val: 39, es: "treinta y nueve" },
    { val: 40, es: "cuarenta" },
    { val: 41, es: "cuarenta y uno" },
    { val: 42, es: "cuarenta y dos" },
    { val: 43, es: "cuarenta y tres" },
    { val: 44, es: "cuarenta y cuatro" },
    { val: 45, es: "cuarenta y cinco" },
    { val: 46, es: "cuarenta y seis" },
    { val: 47, es: "cuarenta y siete" },
    { val: 48, es: "cuarenta y ocho" },
    { val: 49, es: "cuarenta y nueve" },
    { val: 50, es: "cincuenta" },
    { val: 51, es: "cincuenta y uno" },
    { val: 52, es: "cincuenta y dos" },
    { val: 53, es: "cincuenta y tres" },
    { val: 54, es: "cincuenta y cuatro" },
    { val: 55, es: "cincuenta y cinco" },
    { val: 56, es: "cincuenta y seis" },
    { val: 57, es: "cincuenta y siete" },
    { val: 58, es: "cincuenta y ocho" },
    { val: 59, es: "cincuenta y nueve" },
    { val: 60, es: "sesenta" },
    { val: 61, es: "sesenta y uno" },
    { val: 62, es: "sesenta y dos" },
    { val: 63, es: "sesenta y tres" },
    { val: 64, es: "sesenta y cuatro" },
    { val: 65, es: "sesenta y cinco" },
    { val: 66, es: "sesenta y seis" },
    { val: 67, es: "sesenta y siete" },
    { val: 68, es: "sesenta y ocho" },
    { val: 69, es: "sesenta y nueve" },
    { val: 70, es: "setenta" },
    { val: 71, es: "setenta y uno" },
    { val: 72, es: "setenta y dos" },
    { val: 73, es: "setenta y tres" },
    { val: 74, es: "setenta y cuatro" },
    { val: 75, es: "setenta y cinco" },
    { val: 76, es: "setenta y seis" },
    { val: 77, es: "setenta y siete" },
    { val: 78, es: "setenta y ocho" },
    { val: 79, es: "setenta y nueve" },
    { val: 80, es: "ochenta" },
    { val: 81, es: "ochenta y uno" },
    { val: 82, es: "ochenta y dos" },
    { val: 83, es: "ochenta y tres" },
    { val: 84, es: "ochenta y cuatro" },
    { val: 85, es: "ochenta y cinco" },
    { val: 86, es: "ochenta y seis" },
    { val: 87, es: "ochenta y siete" },
    { val: 88, es: "ochenta y ocho" },
    { val: 89, es: "ochenta y nueve" },
    { val: 90, es: "noventa" },
    { val: 91, es: "noventa y uno" },
    { val: 92, es: "noventa y dos" },
    { val: 93, es: "noventa y tres" },
    { val: 94, es: "noventa y cuatro" },
    { val: 95, es: "noventa y cinco" },
    { val: 96, es: "noventa y seis" },
    { val: 97, es: "noventa y siete" },
    { val: 98, es: "noventa y ocho" },
    { val: 99, es: "noventa y nueve" },
    { val: 100, es: "cien" },
  ]
};

export const WRITING_DATA: Record<string, any[]> = {
  modulo1: [
    { es: "Hola", en: "Hello" },
    { es: "Adiós", en: "Goodbye" },
    { es: "Gracias", en: "Thank you" },
    { es: "Por favor", en: "Please" },
    { es: "Sí", en: "Yes" },
    { es: "No", en: "No" },
    { es: "Yo soy", en: "I am" },
    { es: "Tú eres", en: "You are" },
    { es: "Él es", en: "He is" },
    { es: "Ella es", en: "She is" },
    { es: "Usted es", en: "You (formal) are" },
    { es: "Nosotros somos", en: "We are" },
    { es: "Ellos son", en: "They are" },
    { es: "Ustedes son", en: "You all are" },
    { es: "uno", en: "one" },
  ],
  modulo2: [
    { es: "Casa", en: "House" },
    { es: "Ciudad", en: "City" },
    { es: "Familia", en: "Family" },
    { es: "Perro", en: "Dog" },
    { es: "Gato", en: "Cat" },
    { es: "Libro", en: "Book" },
    { es: "Escuela", en: "School" },
    { es: "Parque", en: "Park" },
    { es: "Padre", en: "Father" },
    { es: "Madre", en: "Mother" },
    { es: "Hermano", en: "Brother" },
    { es: "Hermana", en: "Sister" },
    { es: "Abuelo", en: "Grandfather" },
    { es: "Abuela", en: "Grandmother" },
    { es: "Maestro", en: "Teacher" },
  ],
  verbos_comunes_100: [
    { es: "ser", en: "to be" },
    { es: "estar", en: "to be (location/state)" },
    { es: "tener", en: "to have" },
    { es: "hacer", en: "to do/make" },
    { es: "ir", en: "to go" },
    { es: "decir", en: "to say/tell" },
    { es: "poder", en: "to be able to" },
    { es: "ver", en: "to see" },
    { es: "dar", en: "to give" },
    { es: "saber", en: "to know (facts)" },
  ],
  ...VOCAB_DATA,
};

export const COMMON_VERBS_100_DATA = {
  all: [
    { es: "ser", en: "to be" },
    { es: "estar", en: "to be (location/state)" },
    { es: "tener", en: "to have" },
    { es: "hacer", en: "to do/make" },
    { es: "ir", en: "to go" },
    { es: "decir", en: "to say/tell" },
    { es: "poder", en: "to be able to" },
    { es: "ver", en: "to see" },
    { es: "dar", en: "to give" },
    { es: "saber", en: "to know (facts)" },
    { es: "querer", en: "to want" },
    { es: "llegar", en: "to arrive" },
    { es: "pasar", en: "to pass/happen" },
    { es: "deber", en: "should/must" },
    { es: "poner", en: "to put" },
    { es: "parecer", en: "to seem" },
    { es: "quedar", en: "to remain/stay" },
    { es: "creer", en: "to believe" },
    { es: "hablar", en: "to speak" },
    { es: "llevar", en: "to carry/take" },
    { es: "dejar", en: "to leave/let" },
    { es: "seguir", en: "to follow" },
    { es: "encontrar", en: "to find" },
    { es: "llamar", en: "to call" },
    { es: "venir", en: "to come" },
    { es: "pensar", en: "to think" },
    { es: "salir", en: "to leave/go out" },
    { es: "volver", en: "to return" },
    { es: "tomar", en: "to take/drink" },
    { es: "conocer", en: "to know (people/places)" },
    { es: "vivir", en: "to live" },
    { es: "sentir", en: "to feel" },
    { es: "tratar", en: "to try/treat" },
    { es: "mirar", en: "to look at" },
    { es: "contar", en: "to count/tell" },
    { es: "empezar", en: "to begin" },
    { es: "esperar", en: "to wait/hope" },
    { es: "buscar", en: "to look for" },
    { es: "existir", en: "to exist" },
    { es: "entrar", en: "to enter" },
    { es: "trabajar", en: "to work" },
    { es: "escribir", en: "to write" },
    { es: "perder", en: "to lose" },
    { es: "producir", en: "to produce" },
    { es: "occurrir", en: "to occur" },
    { es: "entender", en: "to understand" },
    { es: "pedir", en: "to ask for" },
    { es: "recibir", en: "to receive" },
    { es: "recordar", en: "to remember" },
    { es: "terminar", en: "to finish" },
    { es: "permitir", en: "to permit" },
    { es: "aparecer", en: "to appear" },
    { es: "conseguir", en: "to get/obtain" },
    { es: "comenzar", en: "to start" },
    { es: "servir", en: "to serve" },
    { es: "sacar", en: "to take out" },
    { es: "necesitar", en: "to need" },
    { es: "mantener", en: "to maintain" },
    { es: "resultar", en: "to result" },
    { es: "leer", en: "to read" },
    { es: "caer", en: "to fall" },
    { es: "cambiar", en: "to change" },
    { es: "presentar", en: "to present" },
    { es: "crear", en: "to create" },
    { es: "abrir", en: "to open" },
    { es: "considerar", en: "to consider" },
    { es: "oír", en: "to hear" },
    { es: "acabar", en: "to finish" },
    { es: "convertir", en: "to convert" },
    { es: "ganar", en: "to win/earn" },
    { es: "formar", en: "to form" },
    { es: "morir", en: "to die" },
    { es: "aceptar", en: "to accept" },
    { es: "realizar", en: "to realize/perform" },
    { es: "suponer", en: "to suppose" },
    { es: "comprender", en: "to understand" },
    { es: "lograr", en: "to achieve" },
    { es: "explicar", en: "to explain" },
    { es: "preguntar", en: "to ask" },
    { es: "tocar", en: "to touch/play (instrument)" },
    { es: "estudiar", en: "to study" },
    { es: "correr", en: "to run" },
    { es: "luchar", en: "to fight" },
    { es: "montar", en: "to ride" },
    { es: "viajar", en: "to travel" },
    { es: "ayudar", en: "to help" },
    { es: "comprar", en: "to buy" },
    { es: "vender", en: "to sell" },
    { es: "aprender", en: "to learn" },
    { es: "enseñar", en: "to teach" },
    { es: "escuchar", en: "to listen" },
    { es: "comer", en: "to eat" },
    { es: "beber", en: "to drink" },
    { es: "dormir", en: "to sleep" },
    { es: "jugar", en: "to play" },
    { es: "cantar", en: "to sing" },
    { es: "bailar", en: "to dance" },
    { es: "saltar", en: "to jump" },
    { es: "nadar", en: "to swim" },
    { es: "subir", en: "to go up/upload" },
    { es: "bajar", en: "to go down/download" },
    { es: "entrenar", en: "to train" },
    { es: "practicar", en: "to practice" },
    { es: "decidir", en: "to decide" },
    { es: "compartir", en: "to share" },
  ]
};
